var mediaWikiLoadStart = (new Date()).getTime(),
	mwPerformance = (window.performance && performance.mark) ? performance : {
		mark: function() {}
	};
mwPerformance.mark('mwLoadStart');

function isCompatible(str) {
	var ua = str || navigator.userAgent;
	return !!('querySelector' in document && 'localStorage' in window && 'addEventListener' in window && !(ua.match(/webOS\/1\.[0-4]/) || ua.match(/PlayStation/i) || ua.match(/SymbianOS|Series60|NetFront|Opera Mini|S40OviBrowser|MeeGo/) || (ua.match(/Glass/) && ua.match(/Android/))));
}(function() {
	var NORLQ, script;
	if(!isCompatible()) {
		document.documentElement.className = document.documentElement.className.replace(/(^|\s)client-js(\s|$)/, '$1client-nojs$2');
		NORLQ = window.NORLQ || [];
		while(NORLQ.length) {
			NORLQ.shift()();
		}
		window.NORLQ = {
			push: function(fn) {
				fn();
			}
		};
		window.RLQ = {
			push: function() {}
		};
		return;
	}

	function startUp() {
		mw.config = new mw.Map(true);
		mw.loader.addSource({
			"local": "//wikicdn.joyme.com/xysw/load.php"
		});
		mw.loader.register([
			["site", "CFR7kv+m"],
			["noscript", "wrAvjE1t", [], "noscript"],
			["filepage",
				"HxJ2X4Zx"
			],
			["user.groups", "NrSEgPbt", [], "user"],
			["user", "L9HZ7Vp9", [], "user"],
			["user.cssprefs", "GqV9IPpY", [], "private"],
			["user.defaults", "mnbiR1EL"],
			["user.options", "aVlPDHl0", [6], "private"],
			["user.tokens", "9S8R7E0P", [], "private"],
			["mediawiki.language.data", "VaUbcFmT", [174]],
			["mediawiki.skinning.elements", "5l4KOH3q"],
			["mediawiki.skinning.content", "8qh+0uK9"],
			["mediawiki.skinning.interface", "P86HkeHU"],
			["mediawiki.skinning.content.parsoid", "+I0AlSt8"],
			["mediawiki.skinning.content.externallinks", "BQsHCtCf"],
			["jquery.accessKeyLabel", "T004kp82", [25, 130]],
			["jquery.appear", "20x0jIYY"],
			["jquery.arrowSteps", "mo4SDFAJ"],
			["jquery.async", "3pi5bCPz"],
			["jquery.autoEllipsis", "xbvE7t+r", [37]],
			["jquery.badge", "ziYWC2sC", [171]],
			["jquery.byteLength", "f09dlyAk"],
			["jquery.byteLimit", "noIxohH9", [21]],
			["jquery.checkboxShiftClick", "Rv5Iailx"],
			["jquery.chosen", "sJ9TCV7A"],
			["jquery.client", "hclERD9E"],
			["jquery.color", "m+DmGY/G", [27]],
			["jquery.colorUtil", "PRlkRT7f"],
			["jquery.confirmable", "UPvhNaJE", [175]],
			[
				"jquery.cookie", "Uu5z5vzn"
			],
			["jquery.expandableField", "G1ovXbfL"],
			["jquery.farbtastic", "G3rDpP7Y", [27]],
			["jquery.footHovzer", "1teMTn1v"],
			["jquery.form", "mb6jsXRZ"],
			["jquery.fullscreen", "N7asxkao"],
			["jquery.getAttrs", "Aoqh7zZg"],
			["jquery.hidpi", "efjFYgpz"],
			["jquery.highlightText", "YzL0HgOQ", [242, 130]],
			["jquery.hoverIntent", "6YSpLL8b"],
			["jquery.i18n", "uHUc2Omr", [173]],
			["jquery.localize", "hNHYp2N1"],
			["jquery.makeCollapsible", "YdvqjJoO"],
			["jquery.mockjax", "THKCEw9m"],
			["jquery.mw-jump", "PqB23PGP"],
			["jquery.mwExtension", "+zurZmH1"],
			["jquery.placeholder", "Hm7Bq6OU"],
			["jquery.qunit", "cq6Gjaut"],
			["jquery.qunit.completenessTest", "us3C4YDN", [46]],
			["jquery.spinner", "C4jkyokS"],
			["jquery.jStorage", "9vCsRliD", [92]],
			["jquery.suggestions", "9tJPHYro", [37]],
			["jquery.tabIndex", "9RjbLdY1"],
			["jquery.tablesorter", "WbTWVDvC", [242, 130, 176]],
			["jquery.textSelection", "AjP3apbw", [25]],
			["jquery.throttle-debounce", "CjigaBxa"],
			["jquery.xmldom", "tVljXeGS"],
			["jquery.tipsy", "vxepwbOv"],
			["jquery.ui.core", "eH6Xg/c2", [58],
				"jquery.ui"
			],
			["jquery.ui.core.styles", "HITsWwsI", [], "jquery.ui"],
			["jquery.ui.accordion", "6w6Xv/W+", [57, 77], "jquery.ui"],
			["jquery.ui.autocomplete", "V5WPygE6", [66], "jquery.ui"],
			["jquery.ui.button", "sDKzMEhZ", [57, 77], "jquery.ui"],
			["jquery.ui.datepicker", "OnOnqcjW", [57], "jquery.ui"],
			["jquery.ui.dialog", "psktsoRP", [61, 64, 68, 70], "jquery.ui"],
			["jquery.ui.draggable", "D7sC+T4x", [57, 67], "jquery.ui"],
			["jquery.ui.droppable", "ydbvRXY/", [64], "jquery.ui"],
			["jquery.ui.menu", "pnHcJ4U0", [57, 68, 77], "jquery.ui"],
			["jquery.ui.mouse", "qKRaqD6D", [77], "jquery.ui"],
			["jquery.ui.position", "sytK3I6v", [], "jquery.ui"],
			["jquery.ui.progressbar", "KQR0A7Mj", [57, 77], "jquery.ui"],
			["jquery.ui.resizable", "83bYF1YX", [57, 67], "jquery.ui"],
			["jquery.ui.selectable", "ONgWwF2n", [57, 67], "jquery.ui"],
			["jquery.ui.slider", "dVtQ/mNt", [57, 67], "jquery.ui"],
			["jquery.ui.sortable", "Wv9dNDPl", [57, 67], "jquery.ui"],
			["jquery.ui.spinner", "MzbXkQ9V", [61], "jquery.ui"],
			["jquery.ui.tabs", "AzsNeqGK", [57, 77], "jquery.ui"],
			["jquery.ui.tooltip", "PJcdhakD", [57, 68, 77], "jquery.ui"],
			["jquery.ui.widget", "rP/GVMSg", [], "jquery.ui"],
			["jquery.effects.core", "AdKymUei", [], "jquery.ui"],
			["jquery.effects.blind", "tLrmwOcK", [78], "jquery.ui"],
			["jquery.effects.bounce", "eL+rukkD", [78], "jquery.ui"],
			["jquery.effects.clip", "iKDaO4Tp", [78], "jquery.ui"],
			["jquery.effects.drop", "+ZAvdGR/", [78], "jquery.ui"],
			["jquery.effects.explode", "G2fDgv9L", [78], "jquery.ui"],
			["jquery.effects.fade", "IJ26ds1y", [78], "jquery.ui"],
			["jquery.effects.fold", "iYIQ3I+C", [78], "jquery.ui"],
			["jquery.effects.highlight", "mnA0b85+", [78], "jquery.ui"],
			["jquery.effects.pulsate", "pH+jr/BE", [78], "jquery.ui"],
			["jquery.effects.scale", "ST6S0mVQ", [78], "jquery.ui"],
			["jquery.effects.shake", "nVZP8T8d", [78], "jquery.ui"],
			["jquery.effects.slide", "byAbsCn/", [78], "jquery.ui"],
			["jquery.effects.transfer", "WU25dT8Z", [78], "jquery.ui"],
			["json", "xcOgVRZs", [], null, null, "return!!(window.JSON\u0026\u0026JSON.stringify\u0026\u0026JSON.parse);"],
			["moment", "wQhhYKFO"],
			["mediawiki.apihelp", "z6u2Kxkb"],
			[
				"mediawiki.template", "xfz68Ejm"
			],
			["mediawiki.template.mustache", "9LGcwX0f", [95]],
			["mediawiki.template.regexp", "yKKl3P/R", [95]],
			["mediawiki.apipretty", "5DHgPZRt"],
			["mediawiki.api", "E+ER9iV/", [147, 8]],
			["mediawiki.api.category", "jCBRnaZQ", [135, 99]],
			["mediawiki.api.edit", "+9sp9gNr", [135, 99]],
			["mediawiki.api.login", "1mQq3+LS", [99]],
			["mediawiki.api.options", "nsTPG7Pq", [99]],
			["mediawiki.api.parse", "rdhcW/ZW", [99]],
			["mediawiki.api.upload", "BmJelxbf", [242, 92, 101]],
			["mediawiki.api.user", "3aH6QfMr", [99]],
			["mediawiki.api.watch", "9FegRs7u", [99]],
			["mediawiki.api.messages", "G9HY8aO1", [99]],
			["mediawiki.content.json", "zi9vsBcF"],
			["mediawiki.confirmCloseWindow", "DeTTILnf"],
			["mediawiki.debug", "EuWLf3kY", [32, 56]],
			["mediawiki.debug.init", "dX7PFRcF", [111]],
			["mediawiki.feedback", "DgBJrt57", [135, 126, 250]],
			["mediawiki.feedlink", "suE38nZl"],
			["mediawiki.filewarning", "xP2C1vVH", [245]],
			["mediawiki.ForeignApi", "++nj4aVJ", [117]],
			["mediawiki.ForeignApi.core", "SE01oq88", [99, 243]],
			["mediawiki.helplink", "LtfbZ0JC"],
			[
				"mediawiki.hidpi", "rAk2j7KU", [36], null, null, "return'srcset'in new Image();"
			],
			["mediawiki.hlist", "9o0ZuidE"],
			["mediawiki.htmlform", "W1o9hpFD", [22, 130]],
			["mediawiki.htmlform.styles", "K+oayWRy"],
			["mediawiki.htmlform.ooui.styles", "0qkQLbdY"],
			["mediawiki.icon", "A3RafHBA"],
			["mediawiki.inspect", "Yx2vF4hW", [21, 92, 130]],
			["mediawiki.messagePoster", "jQaabIs6", [116]],
			["mediawiki.messagePoster.wikitext", "7yI3d2Fb", [101, 126]],
			["mediawiki.notification", "oq95nYlZ", [183]],
			["mediawiki.notify", "G4E3gcYh"],
			["mediawiki.RegExp", "5d3o0aga"],
			["mediawiki.pager.tablePager", "55yb7OQw"],
			["mediawiki.searchSuggest", "sUiPcQsN", [35, 45, 50, 99]],
			["mediawiki.sectionAnchor", "3tMtnJ/M"],
			["mediawiki.storage", "j8cQM5/n"],
			["mediawiki.Title", "7owkxbXv", [21, 147]],
			["mediawiki.Upload", "7NEAjtTO", [105]],
			["mediawiki.ForeignUpload", "+p1X4+B7", [116, 136]],
			["mediawiki.ForeignStructuredUpload.config", "JtmRymYi"],
			["mediawiki.ForeignStructuredUpload", "/idWD3Y7", [138, 137]],
			["mediawiki.Upload.Dialog", "oxxm9vLb", [141]],
			[
				"mediawiki.Upload.BookletLayout", "+sgORf3r", [136, 175, 145, 240, 93, 250, 256, 257]
			],
			["mediawiki.ForeignStructuredUpload.BookletLayout", "IETAvscZ", [139, 141, 108, 179, 236, 234]],
			["mediawiki.toc", "Lbwr9Sag", [151]],
			["mediawiki.Uri", "W1Rte7ng", [147, 97]],
			["mediawiki.user", "IxnKQogF", [106, 151, 7]],
			["mediawiki.userSuggest", "OjNWRKhV", [50, 99]],
			["mediawiki.util", "1w13mgre", [15, 129]],
			["mediawiki.viewport", "0Qae4ZMZ"],
			["mediawiki.checkboxtoggle", "yJzQO9IY"],
			["mediawiki.checkboxtoggle.styles", "WAXL70VM"],
			["mediawiki.cookie", "G367KSMd", [29]],
			["mediawiki.toolbar", "2iylBA3l"],
			["mediawiki.experiments", "rxCu4eXl"],
			["mediawiki.raggett", "qrL+10iT"],
			["mediawiki.action.edit", "+QJBalY2", [22, 53, 156]],
			["mediawiki.action.edit.styles", "B5Kshf5g"],
			["mediawiki.action.edit.collapsibleFooter", "jj4A2deX", [41, 151, 124]],
			["mediawiki.action.edit.preview", "WGQr0N4r", [33, 48, 53, 161, 99, 175]],
			["mediawiki.action.edit.stash", "Y94M6wZV", [35, 99]],
			["mediawiki.action.history", "DtkjR3Bv"],
			["mediawiki.action.history.diff", "cn+AasiP"],
			[
				"mediawiki.action.view.dblClickEdit", "WULevKU+", [183, 7]
			],
			["mediawiki.action.view.metadata", "NRg9lIx2"],
			["mediawiki.action.view.categoryPage.styles", "aJ7vLjJV"],
			["mediawiki.action.view.postEdit", "iKLp0uf3", [151, 175, 95]],
			["mediawiki.action.view.redirect", "A56jEhNj", [25]],
			["mediawiki.action.view.redirectPage", "jIl7SbTC"],
			["mediawiki.action.view.rightClickEdit", "qXAnJQHw"],
			["mediawiki.action.edit.editWarning", "DFFK6Qez", [53, 110, 175]],
			["mediawiki.action.view.filepage", "osDwNxYD"],
			["mediawiki.language", "GWPZKS1W", [172, 9]],
			["mediawiki.cldr", "X1Bxwd0x", [173]],
			["mediawiki.libs.pluralruleparser", "lzotNfXM"],
			["mediawiki.language.init", "ydf72/K4"],
			["mediawiki.jqueryMsg", "3BFJOerX", [242, 171, 147, 7]],
			["mediawiki.language.months", "1/Yjl3tz", [171]],
			["mediawiki.language.names", "3z+s6y7q", [174]],
			["mediawiki.language.specialCharacters", "HxTPtlhB", [171]],
			["mediawiki.libs.jpegmeta", "z6J7IXKn"],
			["mediawiki.page.gallery", "5B9mdF3J", [54, 181]],
			["mediawiki.page.gallery.styles", "/2NVnKg8"],
			["mediawiki.page.ready", "gWxT8fei", [15, 23, 41, 43, 45]],
			["mediawiki.page.startup", "vAlIafdc", [147]],
			["mediawiki.page.patrol.ajax", "80/AasaB", [48, 135, 99, 183]],
			["mediawiki.page.watch.ajax", "Ptb7q3DB", [107, 183]],
			["mediawiki.page.image.pagination", "/0U22Mk+", [48, 147]],
			["mediawiki.special", "cTJd9HfV"],
			["mediawiki.special.apisandbox.styles", "MyJb2vYh"],
			["mediawiki.special.apisandbox", "L4WP80K5", [99, 175, 187, 235, 244]],
			["mediawiki.special.block", "eSWEOm6P", [147]],
			["mediawiki.special.blocklist", "apkipSAr"],
			["mediawiki.special.changeslist", "+/PTxT7r"],
			["mediawiki.special.changeslist.legend", "5QnQnrIo"],
			["mediawiki.special.changeslist.legend.js", "SFH/S57c", [41, 151]],
			["mediawiki.special.changeslist.enhanced", "mdN1nYBI"],
			["mediawiki.special.changeslist.visitedstatus", "gksQd5/P"],
			["mediawiki.special.comparepages.styles", "FJJToqNK"],
			["mediawiki.special.edittags", "xydaZaeS", [24]],
			["mediawiki.special.edittags.styles", "xEu1yO3A"],
			["mediawiki.special.import", "VXf4dyKb"],
			["mediawiki.special.movePage", "87Fc2MHp", [232]],
			[
				"mediawiki.special.movePage.styles", "qjG4aiLl"
			],
			["mediawiki.special.pageLanguage", "rUkekYbp", [245]],
			["mediawiki.special.pagesWithProp", "JudcZ8Nj"],
			["mediawiki.special.preferences", "lALNkOyA", [110, 171, 128]],
			["mediawiki.special.preferences.styles", "PueWff50"],
			["mediawiki.special.recentchanges", "gl6LEoyE", [187]],
			["mediawiki.special.search", "mbExRo2z", [238]],
			["mediawiki.special.undelete", "dQjhFKbn"],
			["mediawiki.special.upload", "aqcd4zOL", [48, 135, 99, 110, 175, 179, 95]],
			["mediawiki.special.userlogin.common.styles", "CYzrCrmw"],
			["mediawiki.special.userlogin.signup.styles", "20Yvh6Ri"],
			["mediawiki.special.userlogin.login.styles", "fdaCN0a0"],
			["mediawiki.special.userlogin.signup.js", "j3zqL4i9", [54, 99, 175]],
			["mediawiki.special.unwatchedPages", "Q+daa4Lx", [135, 107]],
			["mediawiki.special.watchlist", "lnwj2TyO"],
			["mediawiki.special.version", "uPBIsSUe"],
			["mediawiki.legacy.config", "XviW/gaT"],
			["mediawiki.legacy.commonPrint", "e8Eq03rR"],
			["mediawiki.legacy.protect", "1ZH2k2ZP", [22]],
			["mediawiki.legacy.shared",
				"u7Cgtwsa"
			],
			["mediawiki.legacy.oldshared", "qR5qnNdh"],
			["mediawiki.legacy.wikibits", "NCKfJPCl", [147]],
			["mediawiki.ui", "lVg1XZTy"],
			["mediawiki.ui.checkbox", "E2llQwMh"],
			["mediawiki.ui.radio", "+dIS4T9N"],
			["mediawiki.ui.anchor", "kMq8qve0"],
			["mediawiki.ui.button", "WUWdBmsx"],
			["mediawiki.ui.input", "3QcFXEgD"],
			["mediawiki.ui.icon", "c2zOePAa"],
			["mediawiki.ui.text", "DZ6EVxtZ"],
			["mediawiki.widgets", "QGyXPZsu", [19, 22, 135, 99, 233, 248]],
			["mediawiki.widgets.styles", "33jZ1yYB"],
			["mediawiki.widgets.DateInputWidget", "CKLCeOqo", [93, 248]],
			["mediawiki.widgets.datetime", "6B6BlPgF", [245]],
			["mediawiki.widgets.CategorySelector", "Hm1CsNMX", [116, 135, 248]],
			["mediawiki.widgets.UserInputWidget", "qwdinSqg", [248]],
			["mediawiki.widgets.SearchInputWidget", "uOS6/gEl", [132, 232]],
			["mediawiki.widgets.SearchInputWidget.styles", "nbRHCYMA"],
			["mediawiki.widgets.StashedFileWidget", "NvHHqtXM", [245]],
			["es5-shim", "c3eyPJEk", [], null, null, "return(function(){'use strict';return!this\u0026\u0026!!Function.prototype.bind;}());"],
			[
				"dom-level2-shim", "8NH1VO0x", [], null, null, "return!!window.Node;"
			],
			["oojs", "vLhy4IpH", [241, 92]],
			["oojs-ui", "ZNdFZL/o", [249, 248, 250]],
			["oojs-ui-core", "WKB+IwKv", [171, 243, 246]],
			["oojs-ui-core.styles", "we2lcWvD", [251, 252, 253], null, null, "return!!jQuery('meta[name=\"X-OOUI-PHP\"]').length;"],
			["oojs-ui.styles", "I6JsSUwG", [251, 252, 253], null, null, "return!!jQuery('meta[name=\"X-OOUI-PHP\"]').length;"],
			["oojs-ui-widgets", "sscpdTIC", [245]],
			["oojs-ui-toolbars", "SJoO2VXA", [245]],
			["oojs-ui-windows", "TFzsOD/J", [245]],
			["oojs-ui.styles.icons", "0aBnY1X3"],
			["oojs-ui.styles.indicators", "JAQHY+s/"],
			["oojs-ui.styles.textures", "2bJyxNvO"],
			["oojs-ui.styles.icons-accessibility", "lpmvn9Pb"],
			["oojs-ui.styles.icons-alerts", "WBkjaCxX"],
			["oojs-ui.styles.icons-content", "Y4Itip7X"],
			["oojs-ui.styles.icons-editing-advanced", "xgEomiWp"],
			["oojs-ui.styles.icons-editing-core", "YwI5dVV3"],
			["oojs-ui.styles.icons-editing-list", "VAiuSCTt"],
			["oojs-ui.styles.icons-editing-styling", "ENnR2sM6"],
			["oojs-ui.styles.icons-interactions",
				"tyRp3ITz"
			],
			["oojs-ui.styles.icons-layout", "UsEUxtMK"],
			["oojs-ui.styles.icons-location", "kmwxLp1g"],
			["oojs-ui.styles.icons-media", "yELg4uR6"],
			["oojs-ui.styles.icons-moderation", "ZqoXEK9F"],
			["oojs-ui.styles.icons-movement", "NeSlnZQF"],
			["oojs-ui.styles.icons-user", "62Ud3ngk"],
			["oojs-ui.styles.icons-wikimedia", "epuHhblj"],
			["skins.vector.styles", "HN8I/0Co"],
			["skins.vector.styles.responsive", "StwAJn9Q"],
			["skins.vector.js", "2SSpx/q/", [51, 54]],
			["ext.cite.styles", "mytFoqux"],
			["ext.cite.a11y", "Spg/Ajdp"],
			["ext.cite.style", "JACpVfhS"],
			["ext.cite.visualEditor.core", "9sJTEI3R", [355]],
			["ext.cite.visualEditor.data", "KxDkdgFO", [349]],
			["ext.cite.visualEditor", "nKYdRPvh", [274, 275, 276, 362]],
			["ext.citeThisPage", "TFrLY91O"],
			["ext.inputBox.styles", "ksDRDzmX"],
			["ext.inputBox", "kAWZD9gx", [54]],
			["ext.interwiki.specialpage", "hrP60Oxf", [41]],
			["ext.nuke", "fdPxZode"],
			["mediawiki.api.titleblacklist", "nwBJl1Ue", [99]],
			["jquery.wikiEditor", "JXS+sxJ5", [53, 171], "ext.wikiEditor"],
			["jquery.wikiEditor.dialogs", "rmEWYiwX", [51, 63, 289], "ext.wikiEditor"],
			["jquery.wikiEditor.dialogs.config", "XpMhLCmJ", [50, 285, 142, 140, 95], "ext.wikiEditor"],
			["jquery.wikiEditor.preview", "46oBe+zm", [284, 99], "ext.wikiEditor"],
			["jquery.wikiEditor.publish", "SCxHlq3d", [285], "ext.wikiEditor"],
			["jquery.wikiEditor.toolbar", "wx67Iprv", [18, 29, 284, 291], "ext.wikiEditor"],
			["jquery.wikiEditor.toolbar.config", "361JGrFD", [289, 178], "ext.wikiEditor"],
			["jquery.wikiEditor.toolbar.i18n", "MhvwT5Jm", [], "ext.wikiEditor"],
			["ext.wikiEditor", "mBlOGz4K", [284, 145], "ext.wikiEditor"],
			["ext.wikiEditor.dialogs", "/49rZnYW", [296, 286], "ext.wikiEditor"],
			["ext.wikiEditor.preview", "L2pL1z9L", [292, 287], "ext.wikiEditor"],
			["ext.wikiEditor.publish", "CKn5o/ea", [292, 288], "ext.wikiEditor"],
			["ext.wikiEditor.toolbar", "T60zaXF+", [292, 290], "ext.wikiEditor"],
			["ext.wikiEditor.toolbar.styles", "TDKJr4zb", [], "ext.wikiEditor"],
			["ext.QUser", "LEvkj6uh", [147]],
			["ext.QUser.bind", "cEGN6Q9R", [33]],
			["ext.QDas", "kWtfp2mO", [147]],
			["mmv", "rPntKl57", [26, 34, 36, 54, 56, 144, 175, 306]],
			[
				"mmv.ui.ondemandshareddependencies", "okmh0uPg", [301, 244]
			],
			["mmv.ui.download.pane", "RHZliKYz", [224, 302]],
			["mmv.ui.reuse.shareembed", "p4zpl0hg", [302]],
			["mmv.ui.tipsyDialog", "pkCQ9m2S", [301]],
			["mmv.bootstrap", "EZ70tcSO", [135, 228, 230, 308, 243]],
			["mmv.bootstrap.autostart", "iiLif1D+", [306]],
			["mmv.head", "Dpc9+PD0", [145]],
			["ext.QuickInsert", "ZJJEihDy", [296]],
			["ext.QuickInsert.admin", "R+o2LYyF", [296]],
			["ext.semanticforms.main", "9/3y1n5L", [315, 313, 324, 60, 61, 73]],
			["ext.semanticforms.browser", "B/4Bibij"],
			["ext.semanticforms.fancybox", "X9rFIQRK", [312]],
			["ext.semanticforms.dynatree", "g+vL+9kJ", [77]],
			["ext.semanticforms.autogrow", "JbAOgYSq"],
			["ext.semanticforms.popupformedit", "cljr36nF", [312]],
			["ext.semanticforms.autoedit", "c5UDwKkP"],
			["ext.semanticforms.submit", "7XbKBohi"],
			["ext.semanticforms.collapsible", "KHSgKuVv"],
			["ext.semanticforms.imagepreview", "6vKI7fV/"],
			["ext.semanticforms.checkboxes", "THe1Ag4W"],
			["ext.semanticforms.datepicker", "kVJKsOPW", [311, 62]],
			["ext.semanticforms.regexp", "DYR1W+Zu", [311]],
			["ext.semanticforms.select2", "4Bh4VGAe", [326, 175]],
			["ext.semanticforms.jsgrid", "+LmAy7kB", [73]],
			["ext.semanticforms", "gA3S5Cji"],
			["ext.semanticforms.SF_CreateProperty", "5CFeDoyb"],
			["ext.semanticforms.SF_PageSchemas", "mmenftJS"],
			["ext.semanticforms.SF_CreateTemplate", "oyElW1ay"],
			["ext.semanticforms.SF_CreateClass", "uG10IHwW"],
			["ext.semanticforms.SF_CreateForm", "c/5zjk1s"],
			["Base64.js", "JUEKM6Re"],
			["easy-deflate.core", "MuEHKKbn", [332]],
			["easy-deflate.deflate", "i/1B5Eym", [333]],
			["unicodejs", "O6V2l55d"],
			["unicodejs.wordbreak", "ZNdFZL/o", [335]],
			["papaparse", "eyMDKtKM"],
			["dom-classlist-shim", "U9hRAGte", [], null, null, "return!!('classList'in document.createElement('_')\u0026\u0026!(document.createElementNS\u0026\u0026!('classList'in document.createElementNS('http://www.w3.org/2000/svg','g'))));"],
			["rangefix", "PrD27c4H"],
			["ext.visualEditor.supportCheck", "ICorHmSX"],
			["ext.visualEditor.desktopArticleTarget.init", "0GXKwKIQ", [340, 347, 135, 144, 165, 103, 183, 145]],
			[
				"ext.visualEditor.desktopArticleTarget.noscript", "v9bMuSzZ"
			],
			["ext.visualEditor.targetLoader", "27aVvaHK", [347, 99]],
			["ext.visualEditor.desktopTarget", "DwOrp+a7"],
			["ext.visualEditor.desktopArticleTarget", "m4+UvgfD", [353, 344, 349, 175]],
			["ext.visualEditor.ve", "ayAiY9Ob"],
			["ext.visualEditor.track", "7TyibCle", [346]],
			["ext.visualEditor.base", "H2Ga0BwR", [346, 244, 335]],
			["ext.visualEditor.mediawiki", "naXFS8UZ", [348, 343, 562, 135, 144, 103, 145]],
			["ext.visualEditor.standalone", "CXqkJFXZ", [348, 39, 562]],
			["ext.visualEditor.data", "K+ngSOeo", [349]],
			["ext.visualEditor.core", "qb+DpJhs", [338, 348, 340, 25, 337, 339]],
			["ext.visualEditor.core.desktop", "7flbVKA6", [352]],
			["ext.visualEditor.switching", "8fzkQoAL", [244, 258]],
			["ext.visualEditor.mwcore", "3Waze6kW", [352, 354, 161, 175, 13, 145, 232]],
			["ext.visualEditor.mwformatting", "LbPJ0XXx", [355]],
			["ext.visualEditor.mwimage.core", "4aNmro5S", [355]],
			["ext.visualEditor.mwimage", "cThzncFp", [357, 142, 261, 264, 268]],
			["ext.visualEditor.mwlink", "BJtaWHYJ", [355]],
			[
				"ext.visualEditor.mwmeta", "urvwSNpU", [359, 167]
			],
			["ext.visualEditor.mwtransclusion.core", "LSukrJNd", [355]],
			["ext.visualEditor.mwtransclusion", "lZL+Zhsq", [361, 237]],
			["ext.visualEditor.language", "DLZlee3Z", [352, 562, 177]],
			["ext.visualEditor.mwalienextension", "ruG8ZRPw", [355]],
			["ext.visualEditor.mwgallery", "MO3upaA+", [355, 181, 264]],
			["ext.visualEditor.mwsignature", "IKaK3+cx", [362, 255]],
			["ext.visualEditor.experimental", "ZNdFZL/o", [363]],
			["ext.visualEditor.icons", "h5+z9+/5", [257, 258, 259, 260, 252, 253]],
			["ext.visualEditor.mytool", "xHaHiKWN", [362]],
			["skins.mediawikibootstrap", "ETDT1xbJ"],
			["skins.mediawikibootstrap1", "Xv/W0WFo"],
			["skins.mediawikibootstrap2", "xak2tJI3"],
			["skins.jshare", "zqLvrKQy"],
			["ext.joymescript.LevelTools.js", "cuR0jPF9"],
			["ext.joymescript.year.js", "MeNukZXq"],
			["ext.joymescript.ShowMsg.js", "mowxLGrP"],
			["ext.joymescript.actor-tab.js", "wY6ZANwD"],
			["ext.joymescript.CardSelect.js", "YFebFq4S"],
			["ext.joymescript.CardSelectTr.js", "683aJjJ6"],
			["ext.joymescript.lableLib.js", "RoBoDKD2"],
			[
				"ext.joymescript.rool.js", "hpMKLuA0"
			],
			["ext.joymescript.TabTag.js", "FzMhg+D7"],
			["ext.joymescript.w-lunbo.js", "hx9GSU1M"],
			["ext.joymescript.JoymeMovie.js", "vE2GmKyJ"],
			["ext.joymescript.giffer.js", "yuIyHacn"],
			["ext.joymescript.lunbo.css", "ztDcayCd"],
			["ext.joymescript.lunbo.js", "xGuF8FLD"],
			["ext.joymescript.week.js", "4X+rp1GO"],
			["ext.joymescript.canvas.js", "aQ58N1aQ"],
			["ext.joymescript.zhenrong.js", "sNX5oUGU"],
			["ext.joymescript.timer.js", "cOdjYCKu"],
			["ext.joymescript.counter.js", "xMnQp40I"],
			["ext.joymescript.counter.css", "/mFj0yGf"],
			["ext.ajaxpoll", "8MvSDBxE", [], "ext.ajaxpoll"],
			["ext.Ajaxpoll.New.css", "g8jCByUV"],
			["ext.MsUpload", "gNNKOA/C", [69]],
			["ext.Tabber", "S27H0q6B"],
			["ext.newTabber", "gv9JGiRg"],
			["ext.jlike.js", "sdf68ylY"],
			["ext.jcontribution.css", "Jprhnj9y"],
			["ext.jcontribution.js", "Ss/YeZq2"],
			["ext.jcomments.css", "nmsHQPHh"],
			["ext.jcomments.js", "SMb5l0t7"],
			["ext.jcomments.hot.css", "Kh0C2mj0"],
			["ext.jcomments.hot.js", "dcZjic6e"],
			["ext.voteNY.styles", "vcVeLpEM"],
			["ext.voteNY.scripts",
				"+5KjHely"
			],
			["ext.jquery.easing", "MqhCLD1q"],
			["ext.jquery.fancybox", "hPziNgHv", [408, 415]],
			["ext.jquery.multiselect", "ZLnROMSw", [57, 77]],
			["ext.jquery.multiselect.filter", "Qp9zCpFL", [410]],
			["ext.jquery.blockUI", "n2sKiA7H"],
			["ext.jquery.jqgrid", "ckor/sZR", [415, 57]],
			["ext.jquery.flot", "R0TiW3aA"],
			["ext.jquery.migration.browser", "IzYBOwB5"],
			["ext.srf", "/5xYW4hn", [549], "ext.srf"],
			["ext.srf.api", "VA/sT3QS", [416], "ext.srf"],
			["ext.srf.util", "Ov5fCcjt", [412, 416], "ext.srf"],
			["ext.srf.widgets", "UPkrwgju", [410, 416, 61, 72], "ext.srf"],
			["ext.srf.util.grid", "xIM9Nx9t", [413, 418, 75], "ext.srf"],
			["ext.jquery.sparkline", "vwAFzNgK", [415]],
			["ext.srf.sparkline", "vysUQCOg", [421, 418], "ext.srf"],
			["ext.dygraphs.combined", "t/Jbr54B"],
			["ext.srf.dygraphs", "GsHHCaX/", [423, 553, 418, 18]],
			["ext.jquery.listnav", "epv5/f3N"],
			["ext.jquery.listmenu", "gkaZHLH4"],
			["ext.jquery.pajinate", "Lvg2qcl6"],
			["ext.srf.listwidget", "i5cN7s+j", [418]],
			["ext.srf.listwidget.alphabet", "ZNdFZL/o", [425, 428]],
			["ext.srf.listwidget.menu", "ZNdFZL/o", [
				426, 428
			]],
			["ext.srf.listwidget.pagination", "ZNdFZL/o", [427, 428]],
			["ext.jquery.dynamiccarousel", "2qMXkgWH", [415]],
			["ext.srf.pagewidget.carousel", "CBUnrYyC", [432, 418]],
			["ext.jquery.jqplot.core", "gcnlwGvS", [415]],
			["ext.jquery.jqplot.excanvas", "RirnflM0"],
			["ext.jquery.jqplot.json", "zNKr5a69"],
			["ext.jquery.jqplot.cursor", "MiwboCiI"],
			["ext.jquery.jqplot.logaxisrenderer", "QItrxsFE"],
			["ext.jquery.jqplot.mekko", "I53P6z1N"],
			["ext.jquery.jqplot.bar", "wlHShh28", [434]],
			["ext.jquery.jqplot.pie", "NG+5jKWg", [434]],
			["ext.jquery.jqplot.bubble", "inJ/3G7X", [434]],
			["ext.jquery.jqplot.donut", "JS6FjBra", [441]],
			["ext.jquery.jqplot.pointlabels", "Vb08jFyx", [434]],
			["ext.jquery.jqplot.highlighter", "u7GIFltI", [434]],
			["ext.jquery.jqplot.enhancedlegend", "BEbLGQUM", [434]],
			["ext.jquery.jqplot.trendline", "pb94KQqA"],
			["ext.srf.jqplot.themes", "DrivpGyX", [25]],
			["ext.srf.jqplot.cursor", "ZNdFZL/o", [437, 455]],
			["ext.srf.jqplot.enhancedlegend", "ZNdFZL/o", [446, 455]],
			["ext.srf.jqplot.pointlabels", "ZNdFZL/o", [444, 455]],
			[
				"ext.srf.jqplot.highlighter", "ZNdFZL/o", [445, 455]
			],
			["ext.srf.jqplot.trendline", "ZNdFZL/o", [447, 455]],
			["ext.srf.jqplot.chart", "z2k13P/f", [434, 448, 418, 18]],
			["ext.srf.jqplot.bar", "WaiovtY6", [440, 454]],
			["ext.srf.jqplot.pie", "QAbhHHHh", [441, 454]],
			["ext.srf.jqplot.bubble", "R0tOd1Xf", [442, 454]],
			["ext.srf.jqplot.donut", "QAbhHHHh", [443, 454]],
			["ext.smile.timeline", "o5+AG8ew"],
			["ext.srf.timeline", "NKzlP/1T", [459, 223]],
			["ext.d3.core", "7NPAFGS+"],
			["ext.srf.d3.common", "IdM98CeJ", [418]],
			["ext.d3.wordcloud", "hSHLTJwA", [461, 462]],
			["ext.srf.d3.chart.treemap", "mSJOvi/o", [461, 462]],
			["ext.srf.d3.chart.bubble", "ixyjK+Le", [461, 462]],
			["ext.srf.jquery.progressbar", "I7teYlYy"],
			["ext.srf.jit", "yZCSjp/y"],
			["ext.srf.jitgraph", "UEWB4Sef", [467, 466, 223]],
			["ext.jquery.jcarousel", "lEo4fF/6", [415]],
			["ext.jquery.responsiveslides", "6b3f+Ov8"],
			["ext.srf.formats.gallery", "RqPa8xrC", [418]],
			["ext.srf.gallery.carousel", "8DI0N8+G", [469, 471]],
			["ext.srf.gallery.slideshow", "2qVUPHnp", [470, 471]],
			["ext.srf.gallery.overlay",
				"pq3FXF02", [409, 471]
			],
			["ext.srf.gallery.redirect", "OPpm7L9P", [471]],
			["ext.jquery.fullcalendar", "QThj9uMa"],
			["ext.jquery.gcal", "smcB0hzJ"],
			["ext.srf.widgets.eventcalendar", "moD32UzF", [553, 417, 418, 62, 72]],
			["ext.srf.hooks.eventcalendar", "/f0a9tMw", [416]],
			["ext.srf.eventcalendar", "bSE1Bkk2", [476, 479, 478]],
			["ext.srf.filtered", "lvWwSnsF"],
			["ext.srf.filtered.list-view", "/prPK+Q+", [481]],
			["ext.srf.filtered.table-view", "5MnH67ut", [481]],
			["ext.srf.filtered.calendar-view", "Rw9DbG+P", [476, 481]],
			["ext.srf.filtered.value-filter", "uua8gAuQ", [481]],
			["ext.srf.filtered.distance-filter", "5m0glKKP", [481, 72]],
			["ext.srf.slideshow", "FmTA56NB", ["mediawiki.legacy.ajax"]],
			["ext.jquery.tagcanvas", "ND55TuW/"],
			["ext.srf.formats.tagcloud", "qxihsXhX", [418]],
			["ext.srf.flot.core", "FLGdXndz"],
			["ext.srf.timeseries.flot", "EiQKSkdT", [414, 490, 418, 18]],
			["ext.jquery.jplayer", "VhPYUqdf"],
			["ext.jquery.jplayer.skin.blue.monday", "VzJFHo1K"],
			["ext.jquery.jplayer.skin.morning.light", "9ccGeh5j"],
			["ext.jquery.jplayer.playlist",
				"4YXBwg0h", [492]
			],
			["ext.jquery.jplayer.inspector", "LVrrsFe0", [492]],
			["ext.srf.template.jplayer", "f9WFQKld", [416]],
			["ext.srf.formats.media", "XC9XKx/9", [495, 497], "ext.srf"],
			["jquery.dataTables", "O8PMnLy+"],
			["jquery.dataTables.extras", "roUo/+Bm"],
			["ext.srf.datatables", "7nXRSKGa", [417, 418, 419, 499, 500]],
			["ext.srf.datatables.bootstrap", "XojRdZxU", [501]],
			["ext.srf.datatables.basic", "FmriOpHd", [501]],
			["ext.scribunto.errors", "Snu4JOpB", [63]],
			["ext.scribunto.logs", "lWyd5uTv"],
			["ext.scribunto.edit", "g+hsxMgJ", [48, 99]],
			["ext.socialprofile.userinfo.css", "rYr/gsNL"],
			["ext.socialprofile.userinfo.js", "CJWy/lfX"],
			["ext.socialprofile.clearfix", "mzUSwISP"],
			["ext.socialprofile.responsive", "9+w8dXSr"],
			["ext.socialprofile.flash", "l+QDQHj5"],
			["ext.socialprofile.LightBox", "+mgzw8Zu"],
			["ext.socialprofile.userboard.js", "OIcO4fJf", [244]],
			["ext.socialprofile.userboard.css", "PRCue6y6"],
			["ext.socialprofile.userboard.headskin.css", "lRdEI50R"],
			["ext.socialprofile.userboard.boardlist.css", "cbNHSVm5"],
			[
				"ext.socialprofile.userboard.boardlist.js", "GnbnLi/s", [244]
			],
			["ext.socialprofile.userrelationship.css", "c6o6I5dF"],
			["ext.socialprofile.userrelationship.js", "dn1HhawG"],
			["ext.socialprofile.userstats.css", "sO//PcM2"],
			["ext.socialprofile.useruserfollows.js", "K9kCkekd", [244]],
			["ext.socialprofile.useruserfollows.css", "nxFuLmc7"],
			["ext.socialprofile.userprofile.usercenter.js", "req26jU8"],
			["ext.socialprofile.userprofile.usercenter.css", "exUVbbd6"],
			["ext.socialprofile.userprofile.usercentercommon.css", "6Qgzwm7g"],
			["ext.socialprofile.userprofile.useraccount.css", "y2JIIjFK"],
			["ext.socialprofile.userprofile.useraccount.js", "taRDzaK8", [244]],
			["ext.socialprofile.userprofile.useruploadimg.js", "ceHY9ymg", [244]],
			["ext.socialprofile.userprofile.binderror.js", "lkGQVRZq", [244]],
			["ext.socialprofile.userprofile.action.js", "WuhRYQEx"],
			["ext.socialprofile.userprofile.bootstrap-datetimepicker.css", "gED2JHjx"],
			["ext.socialprofile.userprofile.bootstrap-datetimepicker.js", "optVGleR"],
			[
				"ext.socialprofile.userprofile.edit-select.css", "lZwQpr5B"
			],
			["ext.socialprofile.userprofile.uploadPreview.js", "PTfPV3NZ"],
			["ext.socialprofile.userprofile.jQuery.fileupload.css", "NwBJQwDE"],
			["ext.socialprofile.userprofile.userprofilepage.js", "AdluCn4X"],
			["ext.QuickMessage.js", "cjPTitIz"],
			["ext.QuickMessage.css", "utX63Nvs"],
			["ext.joymerecentchanges", "w5YUVJm5"],
			["ext.smw", "8j7dgFcY", [542], "ext.smw"],
			["ext.smw.style", "2TASgm6A", [552], "ext.smw"],
			["ext.jquery.async", "/XrXZ/hg", [], "ext.smw"],
			["ext.jquery.jStorage", "frGOIC5n", [92], "ext.smw"],
			["ext.jquery.md5", "x9B5fH8i", [], "ext.smw"],
			["ext.smw.dataItem", "9eKqlGqm", [540, 135, 144], "ext.smw"],
			["ext.smw.dataValue", "7RLsdyRO", [545], "ext.smw"],
			["ext.smw.data", "y5thamt2", [546], "ext.smw"],
			["ext.smw.query", "535qB4q2", [540, 147], "ext.smw"],
			["ext.smw.api", "HtRi69jM", [543, 544, 547, 548], "ext.smw"],
			["ext.jquery.qtip.styles", "lGz0Ucax", [], "ext.smw"],
			["ext.jquery.qtip", "2h0bzMku", [550], "ext.smw"],
			["ext.smw.tooltip.styles", "HQWD6PyO", [550], "ext.smw"],
			[
				"ext.smw.tooltip", "0TfjTr2D", [551, 540, 552], "ext.smw"
			],
			["ext.smw.tooltips", "ZNdFZL/o", [541, 553], "ext.smw"],
			["ext.smw.autocomplete", "yPCbU258", [60], "ext.smw"],
			["ext.smw.ask", "gz4p81fF", [555, 541, 553], "ext.smw"],
			["ext.smw.browse", "J8z6rJ1s", [555, 541], "ext.smw"],
			["ext.smw.property", "dMZmB5l1", [555], "ext.smw"],
			["pdfhandler.messages", "oA8H6Hwk"],
			["ext.semanticforms.wikieditor", "NxkA2a9e", [311, 284]],
			["ext.semanticforms.maps", "S/gCwJ9y"],
			["jquery.uls.data", "D1qWlXDh"]
		]);;
		mw.config.set({
			"wgLoadScript": "//wikicdn.joyme.com/xysw/load.php",
			"debug": !1,
			"skin": "mediawikibootstrap1",
			"stylepath": "//wikicdn.joyme.com/skins",
			"wgUrlProtocols": "bitcoin\\:|ftp\\:\\/\\/|ftps\\:\\/\\/|geo\\:|git\\:\\/\\/|gopher\\:\\/\\/|http\\:\\/\\/|https\\:\\/\\/|irc\\:\\/\\/|ircs\\:\\/\\/|magnet\\:|mailto\\:|mms\\:\\/\\/|news\\:|nntp\\:\\/\\/|redis\\:\\/\\/|sftp\\:\\/\\/|sip\\:|sips\\:|sms\\:|ssh\\:\\/\\/|svn\\:\\/\\/|tel\\:|telnet\\:\\/\\/|urn\\:|worldwind\\:\\/\\/|xmpp\\:|\\/\\/",
			"wgArticlePath": "/xysw/$1",
			"wgScriptPath": "/xysw",
			"wgScriptExtension": ".php",
			"wgScript": "/xysw/index.php",
			"wgSearchType": null,
			"wgVariantArticlePath": !1,
			"wgActionPaths": {},
			"wgServer": "http://wikicdn.joyme.com",
			"wgServerName": "wikicdn.joyme.com",
			"wgUserLanguage": "zh-hans",
			"wgContentLanguage": "zh-hans",
			"wgTranslateNumerals": !0,
			"wgVersion": "1.27.1",
			"wgEnableAPI": !0,
			"wgEnableWriteAPI": !0,
			"wgMainPageTitle": "首页",
			"wgFormattedNamespaces": {
				"-2": "媒体文件",
				"-1": "特殊",
				"0": "",
				"1": "讨论",
				"2": "用户",
				"3": "用户讨论",
				"4": "新游试玩WIKI 新游评测 最新游戏排行榜 新游视频直播",
				"5": "新游试玩WIKI 新游评测 最新游戏排行榜 新游视频直播讨论",
				"6": "文件",
				"7": "文件讨论",
				"8": "MediaWiki",
				"9": "MediaWiki讨论",
				"10": "模板",
				"11": "模板讨论",
				"12": "帮助",
				"13": "帮助讨论",
				"14": "分类",
				"15": "分类讨论",
				"102": "属性",
				"103": "属性讨论",
				"104": "Type",
				"105": "Type talk",
				"106": "Form",
				"107": "Form talk",
				"108": "概念",
				"109": "概念讨论",
				"828": "模块",
				"829": "模块讨论",
				"2300": "Gadget",
				"2301": "Gadget talk",
				"2302": "Gadget definition",
				"2303": "Gadget definition talk",
				"3000": "推荐"
			},
			"wgNamespaceIds": {
				"媒体文件": -2,
				"特殊": -1,
				"": 0,
				"讨论": 1,
				"用户": 2,
				"用户讨论": 3,
				"新游试玩wiki_新游评测_最新游戏排行榜_新游视频直播": 4,
				"新游试玩wiki_新游评测_最新游戏排行榜_新游视频直播讨论": 5,
				"文件": 6,
				"文件讨论": 7,
				"mediawiki": 8,
				"mediawiki讨论": 9,
				"模板": 10,
				"模板讨论": 11,
				"帮助": 12,
				"帮助讨论": 13,
				"分类": 14,
				"分类讨论": 15,
				"属性": 102,
				"属性讨论": 103,
				"type": 104,
				"type_talk": 105,
				"form": 106,
				"form_talk": 107,
				"概念": 108,
				"概念讨论": 109,
				"模块": 828,
				"模块讨论": 829,
				"gadget": 2300,
				"gadget_talk": 2301,
				"gadget_definition": 2302,
				"gadget_definition_talk": 2303,
				"推荐": 3000,
				"媒体": -2,
				"对话": 1,
				"用户对话": 3,
				"图像": 6,
				"档案": 6,
				"image": 6,
				"image_talk": 7,
				"图像对话": 7,
				"图像讨论": 7,
				"档案对话": 7,
				"档案讨论": 7,
				"文件对话": 7,
				"模板对话": 11,
				"帮助对话": 13,
				"分类对话": 15,
				"property": 102,
				"property_talk": 103,
				"concept": 108,
				"concept_talk": 109,
				"media": -2,
				"special": -1,
				"talk": 1,
				"user": 2,
				"user_talk": 3,
				"project": 4,
				"project_talk": 5,
				"file": 6,
				"file_talk": 7,
				"mediawiki_talk": 9,
				"template": 10,
				"template_talk": 11,
				"help": 12,
				"help_talk": 13,
				"category": 14,
				"category_talk": 15,
				"module": 828,
				"module_talk": 829
			},
			"wgContentNamespaces": [0],
			"wgSiteName": "新游试玩WIKI_新游评测_最新游戏排行榜_新游视频直播",
			"wgSiteGameTitle": "",
			"wgDBname": "xyswwiki",
			"wgExtraSignatureNamespaces": [],
			"wgAvailableSkins": {
				"vector": "Vector",
				"mediawikibootstrap": "MediaWikiBootstrap",
				"mediawikibootstrap1": "MediaWikiBootstrap1",
				"mediawikibootstrap2": "MediaWikiBootstrap2",
				"jshare": "JShare",
				"fallback": "Fallback",
				"apioutput": "ApiOutput"
			},
			"wgExtensionAssetsPath": "//wikicdn.joyme.com/extensions",
			"wgCookiePrefix": "homewiki",
			"wgCookieDomain": "",
			"wgCookiePath": "/",
			"wgCookieExpiration": 15552000,
			"wgResourceLoaderMaxQueryLength": -1,
			"wgCaseSensitiveNamespaces": [2302, 2303],
			"wgLegalTitleChars": " %!\"$&'()*,\\-./0-9:;=?@A-Z\\\\\\^_`a-z~+\\u0080-\\uFFFF",
			"wgResourceLoaderStorageVersion": 1,
			"wgResourceLoaderStorageEnabled": !1,
			"wgResourceLoaderLegacyModules": [],
			"wgForeignUploadTargets": [],
			"wgEnableUploads": !0,
			"srf-config": {
				"version": "2.3",
				"settings": {
					"wgThumbLimits": [120, 150, 180, 200, 250, 300],
					"srfgScriptPath": "//wikicdn.joyme.com/extensions/SemanticResultFormats"
				}
			},
			"wgWikiEditorMagicWords": {
				"redirect": "#重定向",
				"img_right": "右",
				"img_left": "左",
				"img_none": "无",
				"img_center": "居中",
				"img_thumbnail": "缩略图",
				"img_framed": "有框",
				"img_frameless": "无框"
			},
			"wgMultimediaViewer": {
				"infoLink": "//mediawiki.org/wiki/Special:MyLanguage/Extension:Media_Viewer/About",
				"discussionLink": "//mediawiki.org/wiki/Special:MyLanguage/Extension_talk:Media_Viewer/About",
				"helpLink": "//mediawiki.org/wiki/Special:MyLanguage/Help:Extension:Media_Viewer",
				"useThumbnailGuessing": !1,
				"durationSamplingFactor": !1,
				"durationSamplingFactorLoggedin": !1,
				"networkPerformanceSamplingFactor": !1,
				"actionLoggingSamplingFactorMap": !1,
				"attributionSamplingFactor": !1,
				"dimensionSamplingFactor": !1,
				"imageQueryParameter": !1,
				"recordVirtualViewBeaconURI": !1,
				"tooltipDelay": 1000
			},
			"wgMediaViewer": !0,
			"wgMediaViewerIsInBeta": !1,
			"wgVisualEditorConfig": {
				"disableForAnons": !1,
				"preferenceModules": {
					"visualeditor-enable-experimental": "ext.visualEditor.experimental"
				},
				"namespaces": [2, 0],
				"signatureNamespaces": [],
				"pluginModules": ["ext.cite.visualEditor"],
				"defaultUserOptions": {
					"defaultthumbsize": 300
				},
				"blacklist": {
					"msie": [
						["<=", 8]
					],
					"android": [
						["<", 3]
					],
					"firefox": [
						["<=", 14]
					],
					"safari": [
						["<=", 6]
					],
					"opera": [
						["<", 12]
					],
					"blackberry": null,
					"silk": null
				},
				"skins": ["vector", "apex", "monobook", "minerva", "blueprint", "mediawikibootstrap", "mediawikibootstrap1", "vector", "joyme1"],
				"tabPosition": "before",
				"tabMessages": {
					"edit": null,
					"editsource": "visualeditor-ca-editsource",
					"create": null,
					"createsource": "visualeditor-ca-createsource",
					"editlocaldescriptionsource": "visualeditor-ca-editlocaldescriptionsource",
					"createlocaldescriptionsource": "visualeditor-ca-createlocaldescriptionsource",
					"editsection": null,
					"editsectionsource": "visualeditor-ca-editsource-section"
				},
				"singleEditTab": !1,
				"showBetaWelcome": !0,
				"enableTocWidget": !1,
				"svgMaxSize": 5120,
				"namespacesWithSubpages": [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
					true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
				],
				"specialBooksources": "特殊:网络书源",
				"restbaseUrl": !1,
				"fullRestbaseUrl": !1,
				"feedbackApiUrl": !1,
				"feedbackTitle": !1
			},
			"smw-config": {
				"version": "2.3.1",
				"settings": {
					"smwgQMaxLimit": 10000,
					"smwgQMaxInlineLimit": 1000,
					"namespace": {
						"属性": 102,
						"属性讨论": 103,
						"Type": 104,
						"Type_talk": 105,
						"概念": 108,
						"概念讨论": 109,
						"": 0,
						"Talk": 1,
						"User": 2,
						"User_talk": 3,
						"Project": 4,
						"Project_talk": 5,
						"File": 6,
						"File_talk": 7,
						"MediaWiki": 8,
						"MediaWiki_talk": 9,
						"Template": 10,
						"Template_talk": 11,
						"Help": 12,
						"Help_talk": 13,
						"Category": 14,
						"Category_talk": 15,
						"推荐": 3000
					}
				},
				"formats": {
					"table": "表格",
					"list": "列表",
					"ol": "有序列表项目",
					"ul": "无序列表项目",
					"category": "类别",
					"embedded": "嵌入型页面内容",
					"template": "模板",
					"feed": "RSS和Atom订阅",
					"csv": "CSV导出",
					"dsv": "DSV导出",
					"json": "JSON导出",
					"rdf": "RDF导出",
					"icalendar": "iCalendar导出",
					"vcard": "vCard导出",
					"bibtex": "BibTeX导出",
					"calendar": "月历",
					"eventcalendar": "事件日历",
					"eventline": "事件轴",
					"timeline": "时间轴",
					"outline": "大纲",
					"gallery": "图库",
					"jqplotchart": "jqPlot图表",
					"jqplotseries": "jqPlot系列",
					"sum": "数值之和",
					"average": "数值的平均值",
					"min": "最小数目",
					"max": "最大数目",
					"median": "数值的中位数",
					"product": "数值的乘积",
					"tagcloud": "标签云",
					"valuerank": "取值排名",
					"array": "数组",
					"tree": "树",
					"ultree": "Ultree",
					"oltree": "Oltree",
					"d3chart": "D3图表",
					"latest": "最近时间",
					"earliest": "最早时间",
					"filtered": "已过滤",
					"slideshow": "幻灯片",
					"timeseries": "时间序列图表",
					"sparkline": "Sparkline图表",
					"listwidget": "列表小工具",
					"pagewidget": "页面小部件",
					"dygraphs": "Dygraphs图表",
					"media": "媒体播放器",
					"datatables": "数据表"
				}
			}
		});
		var RLQ = window.RLQ || [];
		while(RLQ.length) {
			RLQ.shift()();
		}
		window.RLQ = {
			push: function(fn) {
				fn();
			}
		};
		window.NORLQ = {
			push: function() {}
		};
	}
	script = document.createElement('script');
	script.src = "//wikicdn.joyme.com/xysw/load.php?debug=false&lang=zh-hans&modules=jquery%2Cmediawiki&only=scripts&skin=mediawikibootstrap1&version=P3r3aZ%2FE";
	script.onload = script.onreadystatechange = function() {
		if(!script.readyState || /loaded|complete/.test(script.readyState)) {
			script.onload = script.onreadystatechange = null;
			script = null;
			startUp();
		}
	};
	document.getElementsByTagName('head')[0].appendChild(script);
}());
var mediaWikiLoadStart = (new Date()).getTime(),
	mwPerformance = (window.performance && performance.mark) ? performance : {
		mark: function() {}
	};
mwPerformance.mark('mwLoadStart');

function isCompatible(str) {
	var ua = str || navigator.userAgent;
	return !!('querySelector' in document && 'localStorage' in window && 'addEventListener' in window && !(ua.match(/webOS\/1\.[0-4]/) || ua.match(/PlayStation/i) || ua.match(/SymbianOS|Series60|NetFront|Opera Mini|S40OviBrowser|MeeGo/) || (ua.match(/Glass/) && ua.match(/Android/))));
}(function() {
	var NORLQ, script;
	if(!isCompatible()) {
		document.documentElement.className = document.documentElement.className.replace(/(^|\s)client-js(\s|$)/, '$1client-nojs$2');
		NORLQ = window.NORLQ || [];
		while(NORLQ.length) {
			NORLQ.shift()();
		}
		window.NORLQ = {
			push: function(fn) {
				fn();
			}
		};
		window.RLQ = {
			push: function() {}
		};
		return;
	}

	function startUp() {
		mw.config = new mw.Map(true);
		mw.loader.addSource({
			"local": "//wikicdn.joyme.com/xysw/load.php"
		});
		mw.loader.register([
			["site", "CFR7kv+m"],
			["noscript", "wrAvjE1t", [], "noscript"],
			["filepage",
				"HxJ2X4Zx"
			],
			["user.groups", "NrSEgPbt", [], "user"],
			["user", "L9HZ7Vp9", [], "user"],
			["user.cssprefs", "GqV9IPpY", [], "private"],
			["user.defaults", "mnbiR1EL"],
			["user.options", "aVlPDHl0", [6], "private"],
			["user.tokens", "9S8R7E0P", [], "private"],
			["mediawiki.language.data", "VaUbcFmT", [174]],
			["mediawiki.skinning.elements", "5l4KOH3q"],
			["mediawiki.skinning.content", "8qh+0uK9"],
			["mediawiki.skinning.interface", "P86HkeHU"],
			["mediawiki.skinning.content.parsoid", "+I0AlSt8"],
			["mediawiki.skinning.content.externallinks", "BQsHCtCf"],
			["jquery.accessKeyLabel", "T004kp82", [25, 130]],
			["jquery.appear", "20x0jIYY"],
			["jquery.arrowSteps", "mo4SDFAJ"],
			["jquery.async", "3pi5bCPz"],
			["jquery.autoEllipsis", "xbvE7t+r", [37]],
			["jquery.badge", "ziYWC2sC", [171]],
			["jquery.byteLength", "f09dlyAk"],
			["jquery.byteLimit", "noIxohH9", [21]],
			["jquery.checkboxShiftClick", "Rv5Iailx"],
			["jquery.chosen", "sJ9TCV7A"],
			["jquery.client", "hclERD9E"],
			["jquery.color", "m+DmGY/G", [27]],
			["jquery.colorUtil", "PRlkRT7f"],
			["jquery.confirmable", "UPvhNaJE", [175]],
			[
				"jquery.cookie", "Uu5z5vzn"
			],
			["jquery.expandableField", "G1ovXbfL"],
			["jquery.farbtastic", "G3rDpP7Y", [27]],
			["jquery.footHovzer", "1teMTn1v"],
			["jquery.form", "mb6jsXRZ"],
			["jquery.fullscreen", "N7asxkao"],
			["jquery.getAttrs", "Aoqh7zZg"],
			["jquery.hidpi", "efjFYgpz"],
			["jquery.highlightText", "YzL0HgOQ", [242, 130]],
			["jquery.hoverIntent", "6YSpLL8b"],
			["jquery.i18n", "uHUc2Omr", [173]],
			["jquery.localize", "hNHYp2N1"],
			["jquery.makeCollapsible", "YdvqjJoO"],
			["jquery.mockjax", "THKCEw9m"],
			["jquery.mw-jump", "PqB23PGP"],
			["jquery.mwExtension", "+zurZmH1"],
			["jquery.placeholder", "Hm7Bq6OU"],
			["jquery.qunit", "cq6Gjaut"],
			["jquery.qunit.completenessTest", "us3C4YDN", [46]],
			["jquery.spinner", "C4jkyokS"],
			["jquery.jStorage", "9vCsRliD", [92]],
			["jquery.suggestions", "9tJPHYro", [37]],
			["jquery.tabIndex", "9RjbLdY1"],
			["jquery.tablesorter", "WbTWVDvC", [242, 130, 176]],
			["jquery.textSelection", "AjP3apbw", [25]],
			["jquery.throttle-debounce", "CjigaBxa"],
			["jquery.xmldom", "tVljXeGS"],
			["jquery.tipsy", "vxepwbOv"],
			["jquery.ui.core", "eH6Xg/c2", [58],
				"jquery.ui"
			],
			["jquery.ui.core.styles", "HITsWwsI", [], "jquery.ui"],
			["jquery.ui.accordion", "6w6Xv/W+", [57, 77], "jquery.ui"],
			["jquery.ui.autocomplete", "V5WPygE6", [66], "jquery.ui"],
			["jquery.ui.button", "sDKzMEhZ", [57, 77], "jquery.ui"],
			["jquery.ui.datepicker", "OnOnqcjW", [57], "jquery.ui"],
			["jquery.ui.dialog", "psktsoRP", [61, 64, 68, 70], "jquery.ui"],
			["jquery.ui.draggable", "D7sC+T4x", [57, 67], "jquery.ui"],
			["jquery.ui.droppable", "ydbvRXY/", [64], "jquery.ui"],
			["jquery.ui.menu", "pnHcJ4U0", [57, 68, 77], "jquery.ui"],
			["jquery.ui.mouse", "qKRaqD6D", [77], "jquery.ui"],
			["jquery.ui.position", "sytK3I6v", [], "jquery.ui"],
			["jquery.ui.progressbar", "KQR0A7Mj", [57, 77], "jquery.ui"],
			["jquery.ui.resizable", "83bYF1YX", [57, 67], "jquery.ui"],
			["jquery.ui.selectable", "ONgWwF2n", [57, 67], "jquery.ui"],
			["jquery.ui.slider", "dVtQ/mNt", [57, 67], "jquery.ui"],
			["jquery.ui.sortable", "Wv9dNDPl", [57, 67], "jquery.ui"],
			["jquery.ui.spinner", "MzbXkQ9V", [61], "jquery.ui"],
			["jquery.ui.tabs", "AzsNeqGK", [57, 77], "jquery.ui"],
			["jquery.ui.tooltip", "PJcdhakD", [57, 68, 77], "jquery.ui"],
			["jquery.ui.widget", "rP/GVMSg", [], "jquery.ui"],
			["jquery.effects.core", "AdKymUei", [], "jquery.ui"],
			["jquery.effects.blind", "tLrmwOcK", [78], "jquery.ui"],
			["jquery.effects.bounce", "eL+rukkD", [78], "jquery.ui"],
			["jquery.effects.clip", "iKDaO4Tp", [78], "jquery.ui"],
			["jquery.effects.drop", "+ZAvdGR/", [78], "jquery.ui"],
			["jquery.effects.explode", "G2fDgv9L", [78], "jquery.ui"],
			["jquery.effects.fade", "IJ26ds1y", [78], "jquery.ui"],
			["jquery.effects.fold", "iYIQ3I+C", [78], "jquery.ui"],
			["jquery.effects.highlight", "mnA0b85+", [78], "jquery.ui"],
			["jquery.effects.pulsate", "pH+jr/BE", [78], "jquery.ui"],
			["jquery.effects.scale", "ST6S0mVQ", [78], "jquery.ui"],
			["jquery.effects.shake", "nVZP8T8d", [78], "jquery.ui"],
			["jquery.effects.slide", "byAbsCn/", [78], "jquery.ui"],
			["jquery.effects.transfer", "WU25dT8Z", [78], "jquery.ui"],
			["json", "xcOgVRZs", [], null, null, "return!!(window.JSON\u0026\u0026JSON.stringify\u0026\u0026JSON.parse);"],
			["moment", "wQhhYKFO"],
			["mediawiki.apihelp", "z6u2Kxkb"],
			[
				"mediawiki.template", "xfz68Ejm"
			],
			["mediawiki.template.mustache", "9LGcwX0f", [95]],
			["mediawiki.template.regexp", "yKKl3P/R", [95]],
			["mediawiki.apipretty", "5DHgPZRt"],
			["mediawiki.api", "E+ER9iV/", [147, 8]],
			["mediawiki.api.category", "jCBRnaZQ", [135, 99]],
			["mediawiki.api.edit", "+9sp9gNr", [135, 99]],
			["mediawiki.api.login", "1mQq3+LS", [99]],
			["mediawiki.api.options", "nsTPG7Pq", [99]],
			["mediawiki.api.parse", "rdhcW/ZW", [99]],
			["mediawiki.api.upload", "BmJelxbf", [242, 92, 101]],
			["mediawiki.api.user", "3aH6QfMr", [99]],
			["mediawiki.api.watch", "9FegRs7u", [99]],
			["mediawiki.api.messages", "G9HY8aO1", [99]],
			["mediawiki.content.json", "zi9vsBcF"],
			["mediawiki.confirmCloseWindow", "DeTTILnf"],
			["mediawiki.debug", "EuWLf3kY", [32, 56]],
			["mediawiki.debug.init", "dX7PFRcF", [111]],
			["mediawiki.feedback", "DgBJrt57", [135, 126, 250]],
			["mediawiki.feedlink", "suE38nZl"],
			["mediawiki.filewarning", "xP2C1vVH", [245]],
			["mediawiki.ForeignApi", "++nj4aVJ", [117]],
			["mediawiki.ForeignApi.core", "SE01oq88", [99, 243]],
			["mediawiki.helplink", "LtfbZ0JC"],
			[
				"mediawiki.hidpi", "rAk2j7KU", [36], null, null, "return'srcset'in new Image();"
			],
			["mediawiki.hlist", "9o0ZuidE"],
			["mediawiki.htmlform", "W1o9hpFD", [22, 130]],
			["mediawiki.htmlform.styles", "K+oayWRy"],
			["mediawiki.htmlform.ooui.styles", "0qkQLbdY"],
			["mediawiki.icon", "A3RafHBA"],
			["mediawiki.inspect", "Yx2vF4hW", [21, 92, 130]],
			["mediawiki.messagePoster", "jQaabIs6", [116]],
			["mediawiki.messagePoster.wikitext", "7yI3d2Fb", [101, 126]],
			["mediawiki.notification", "oq95nYlZ", [183]],
			["mediawiki.notify", "G4E3gcYh"],
			["mediawiki.RegExp", "5d3o0aga"],
			["mediawiki.pager.tablePager", "55yb7OQw"],
			["mediawiki.searchSuggest", "sUiPcQsN", [35, 45, 50, 99]],
			["mediawiki.sectionAnchor", "3tMtnJ/M"],
			["mediawiki.storage", "j8cQM5/n"],
			["mediawiki.Title", "7owkxbXv", [21, 147]],
			["mediawiki.Upload", "7NEAjtTO", [105]],
			["mediawiki.ForeignUpload", "+p1X4+B7", [116, 136]],
			["mediawiki.ForeignStructuredUpload.config", "JtmRymYi"],
			["mediawiki.ForeignStructuredUpload", "/idWD3Y7", [138, 137]],
			["mediawiki.Upload.Dialog", "oxxm9vLb", [141]],
			[
				"mediawiki.Upload.BookletLayout", "+sgORf3r", [136, 175, 145, 240, 93, 250, 256, 257]
			],
			["mediawiki.ForeignStructuredUpload.BookletLayout", "IETAvscZ", [139, 141, 108, 179, 236, 234]],
			["mediawiki.toc", "Lbwr9Sag", [151]],
			["mediawiki.Uri", "W1Rte7ng", [147, 97]],
			["mediawiki.user", "IxnKQogF", [106, 151, 7]],
			["mediawiki.userSuggest", "OjNWRKhV", [50, 99]],
			["mediawiki.util", "1w13mgre", [15, 129]],
			["mediawiki.viewport", "0Qae4ZMZ"],
			["mediawiki.checkboxtoggle", "yJzQO9IY"],
			["mediawiki.checkboxtoggle.styles", "WAXL70VM"],
			["mediawiki.cookie", "G367KSMd", [29]],
			["mediawiki.toolbar", "2iylBA3l"],
			["mediawiki.experiments", "rxCu4eXl"],
			["mediawiki.raggett", "qrL+10iT"],
			["mediawiki.action.edit", "+QJBalY2", [22, 53, 156]],
			["mediawiki.action.edit.styles", "B5Kshf5g"],
			["mediawiki.action.edit.collapsibleFooter", "jj4A2deX", [41, 151, 124]],
			["mediawiki.action.edit.preview", "WGQr0N4r", [33, 48, 53, 161, 99, 175]],
			["mediawiki.action.edit.stash", "Y94M6wZV", [35, 99]],
			["mediawiki.action.history", "DtkjR3Bv"],
			["mediawiki.action.history.diff", "cn+AasiP"],
			[
				"mediawiki.action.view.dblClickEdit", "WULevKU+", [183, 7]
			],
			["mediawiki.action.view.metadata", "NRg9lIx2"],
			["mediawiki.action.view.categoryPage.styles", "aJ7vLjJV"],
			["mediawiki.action.view.postEdit", "iKLp0uf3", [151, 175, 95]],
			["mediawiki.action.view.redirect", "A56jEhNj", [25]],
			["mediawiki.action.view.redirectPage", "jIl7SbTC"],
			["mediawiki.action.view.rightClickEdit", "qXAnJQHw"],
			["mediawiki.action.edit.editWarning", "DFFK6Qez", [53, 110, 175]],
			["mediawiki.action.view.filepage", "osDwNxYD"],
			["mediawiki.language", "GWPZKS1W", [172, 9]],
			["mediawiki.cldr", "X1Bxwd0x", [173]],
			["mediawiki.libs.pluralruleparser", "lzotNfXM"],
			["mediawiki.language.init", "ydf72/K4"],
			["mediawiki.jqueryMsg", "3BFJOerX", [242, 171, 147, 7]],
			["mediawiki.language.months", "1/Yjl3tz", [171]],
			["mediawiki.language.names", "3z+s6y7q", [174]],
			["mediawiki.language.specialCharacters", "HxTPtlhB", [171]],
			["mediawiki.libs.jpegmeta", "z6J7IXKn"],
			["mediawiki.page.gallery", "5B9mdF3J", [54, 181]],
			["mediawiki.page.gallery.styles", "/2NVnKg8"],
			["mediawiki.page.ready", "gWxT8fei", [15, 23, 41, 43, 45]],
			["mediawiki.page.startup", "vAlIafdc", [147]],
			["mediawiki.page.patrol.ajax", "80/AasaB", [48, 135, 99, 183]],
			["mediawiki.page.watch.ajax", "Ptb7q3DB", [107, 183]],
			["mediawiki.page.image.pagination", "/0U22Mk+", [48, 147]],
			["mediawiki.special", "cTJd9HfV"],
			["mediawiki.special.apisandbox.styles", "MyJb2vYh"],
			["mediawiki.special.apisandbox", "L4WP80K5", [99, 175, 187, 235, 244]],
			["mediawiki.special.block", "eSWEOm6P", [147]],
			["mediawiki.special.blocklist", "apkipSAr"],
			["mediawiki.special.changeslist", "+/PTxT7r"],
			["mediawiki.special.changeslist.legend", "5QnQnrIo"],
			["mediawiki.special.changeslist.legend.js", "SFH/S57c", [41, 151]],
			["mediawiki.special.changeslist.enhanced", "mdN1nYBI"],
			["mediawiki.special.changeslist.visitedstatus", "gksQd5/P"],
			["mediawiki.special.comparepages.styles", "FJJToqNK"],
			["mediawiki.special.edittags", "xydaZaeS", [24]],
			["mediawiki.special.edittags.styles", "xEu1yO3A"],
			["mediawiki.special.import", "VXf4dyKb"],
			["mediawiki.special.movePage", "87Fc2MHp", [232]],
			[
				"mediawiki.special.movePage.styles", "qjG4aiLl"
			],
			["mediawiki.special.pageLanguage", "rUkekYbp", [245]],
			["mediawiki.special.pagesWithProp", "JudcZ8Nj"],
			["mediawiki.special.preferences", "lALNkOyA", [110, 171, 128]],
			["mediawiki.special.preferences.styles", "PueWff50"],
			["mediawiki.special.recentchanges", "gl6LEoyE", [187]],
			["mediawiki.special.search", "mbExRo2z", [238]],
			["mediawiki.special.undelete", "dQjhFKbn"],
			["mediawiki.special.upload", "aqcd4zOL", [48, 135, 99, 110, 175, 179, 95]],
			["mediawiki.special.userlogin.common.styles", "CYzrCrmw"],
			["mediawiki.special.userlogin.signup.styles", "20Yvh6Ri"],
			["mediawiki.special.userlogin.login.styles", "fdaCN0a0"],
			["mediawiki.special.userlogin.signup.js", "j3zqL4i9", [54, 99, 175]],
			["mediawiki.special.unwatchedPages", "Q+daa4Lx", [135, 107]],
			["mediawiki.special.watchlist", "lnwj2TyO"],
			["mediawiki.special.version", "uPBIsSUe"],
			["mediawiki.legacy.config", "XviW/gaT"],
			["mediawiki.legacy.commonPrint", "e8Eq03rR"],
			["mediawiki.legacy.protect", "1ZH2k2ZP", [22]],
			["mediawiki.legacy.shared",
				"u7Cgtwsa"
			],
			["mediawiki.legacy.oldshared", "qR5qnNdh"],
			["mediawiki.legacy.wikibits", "NCKfJPCl", [147]],
			["mediawiki.ui", "lVg1XZTy"],
			["mediawiki.ui.checkbox", "E2llQwMh"],
			["mediawiki.ui.radio", "+dIS4T9N"],
			["mediawiki.ui.anchor", "kMq8qve0"],
			["mediawiki.ui.button", "WUWdBmsx"],
			["mediawiki.ui.input", "3QcFXEgD"],
			["mediawiki.ui.icon", "c2zOePAa"],
			["mediawiki.ui.text", "DZ6EVxtZ"],
			["mediawiki.widgets", "QGyXPZsu", [19, 22, 135, 99, 233, 248]],
			["mediawiki.widgets.styles", "33jZ1yYB"],
			["mediawiki.widgets.DateInputWidget", "CKLCeOqo", [93, 248]],
			["mediawiki.widgets.datetime", "6B6BlPgF", [245]],
			["mediawiki.widgets.CategorySelector", "Hm1CsNMX", [116, 135, 248]],
			["mediawiki.widgets.UserInputWidget", "qwdinSqg", [248]],
			["mediawiki.widgets.SearchInputWidget", "uOS6/gEl", [132, 232]],
			["mediawiki.widgets.SearchInputWidget.styles", "nbRHCYMA"],
			["mediawiki.widgets.StashedFileWidget", "NvHHqtXM", [245]],
			["es5-shim", "c3eyPJEk", [], null, null, "return(function(){'use strict';return!this\u0026\u0026!!Function.prototype.bind;}());"],
			[
				"dom-level2-shim", "8NH1VO0x", [], null, null, "return!!window.Node;"
			],
			["oojs", "vLhy4IpH", [241, 92]],
			["oojs-ui", "ZNdFZL/o", [249, 248, 250]],
			["oojs-ui-core", "WKB+IwKv", [171, 243, 246]],
			["oojs-ui-core.styles", "we2lcWvD", [251, 252, 253], null, null, "return!!jQuery('meta[name=\"X-OOUI-PHP\"]').length;"],
			["oojs-ui.styles", "I6JsSUwG", [251, 252, 253], null, null, "return!!jQuery('meta[name=\"X-OOUI-PHP\"]').length;"],
			["oojs-ui-widgets", "sscpdTIC", [245]],
			["oojs-ui-toolbars", "SJoO2VXA", [245]],
			["oojs-ui-windows", "TFzsOD/J", [245]],
			["oojs-ui.styles.icons", "0aBnY1X3"],
			["oojs-ui.styles.indicators", "JAQHY+s/"],
			["oojs-ui.styles.textures", "2bJyxNvO"],
			["oojs-ui.styles.icons-accessibility", "lpmvn9Pb"],
			["oojs-ui.styles.icons-alerts", "WBkjaCxX"],
			["oojs-ui.styles.icons-content", "Y4Itip7X"],
			["oojs-ui.styles.icons-editing-advanced", "xgEomiWp"],
			["oojs-ui.styles.icons-editing-core", "YwI5dVV3"],
			["oojs-ui.styles.icons-editing-list", "VAiuSCTt"],
			["oojs-ui.styles.icons-editing-styling", "ENnR2sM6"],
			["oojs-ui.styles.icons-interactions",
				"tyRp3ITz"
			],
			["oojs-ui.styles.icons-layout", "UsEUxtMK"],
			["oojs-ui.styles.icons-location", "kmwxLp1g"],
			["oojs-ui.styles.icons-media", "yELg4uR6"],
			["oojs-ui.styles.icons-moderation", "ZqoXEK9F"],
			["oojs-ui.styles.icons-movement", "NeSlnZQF"],
			["oojs-ui.styles.icons-user", "62Ud3ngk"],
			["oojs-ui.styles.icons-wikimedia", "epuHhblj"],
			["skins.vector.styles", "HN8I/0Co"],
			["skins.vector.styles.responsive", "StwAJn9Q"],
			["skins.vector.js", "2SSpx/q/", [51, 54]],
			["ext.cite.styles", "mytFoqux"],
			["ext.cite.a11y", "Spg/Ajdp"],
			["ext.cite.style", "JACpVfhS"],
			["ext.cite.visualEditor.core", "9sJTEI3R", [355]],
			["ext.cite.visualEditor.data", "KxDkdgFO", [349]],
			["ext.cite.visualEditor", "nKYdRPvh", [274, 275, 276, 362]],
			["ext.citeThisPage", "TFrLY91O"],
			["ext.inputBox.styles", "ksDRDzmX"],
			["ext.inputBox", "kAWZD9gx", [54]],
			["ext.interwiki.specialpage", "hrP60Oxf", [41]],
			["ext.nuke", "fdPxZode"],
			["mediawiki.api.titleblacklist", "nwBJl1Ue", [99]],
			["jquery.wikiEditor", "JXS+sxJ5", [53, 171], "ext.wikiEditor"],
			["jquery.wikiEditor.dialogs", "rmEWYiwX", [51, 63, 289], "ext.wikiEditor"],
			["jquery.wikiEditor.dialogs.config", "XpMhLCmJ", [50, 285, 142, 140, 95], "ext.wikiEditor"],
			["jquery.wikiEditor.preview", "46oBe+zm", [284, 99], "ext.wikiEditor"],
			["jquery.wikiEditor.publish", "SCxHlq3d", [285], "ext.wikiEditor"],
			["jquery.wikiEditor.toolbar", "wx67Iprv", [18, 29, 284, 291], "ext.wikiEditor"],
			["jquery.wikiEditor.toolbar.config", "361JGrFD", [289, 178], "ext.wikiEditor"],
			["jquery.wikiEditor.toolbar.i18n", "MhvwT5Jm", [], "ext.wikiEditor"],
			["ext.wikiEditor", "mBlOGz4K", [284, 145], "ext.wikiEditor"],
			["ext.wikiEditor.dialogs", "/49rZnYW", [296, 286], "ext.wikiEditor"],
			["ext.wikiEditor.preview", "L2pL1z9L", [292, 287], "ext.wikiEditor"],
			["ext.wikiEditor.publish", "CKn5o/ea", [292, 288], "ext.wikiEditor"],
			["ext.wikiEditor.toolbar", "T60zaXF+", [292, 290], "ext.wikiEditor"],
			["ext.wikiEditor.toolbar.styles", "TDKJr4zb", [], "ext.wikiEditor"],
			["ext.QUser", "LEvkj6uh", [147]],
			["ext.QUser.bind", "cEGN6Q9R", [33]],
			["ext.QDas", "kWtfp2mO", [147]],
			["mmv", "rPntKl57", [26, 34, 36, 54, 56, 144, 175, 306]],
			[
				"mmv.ui.ondemandshareddependencies", "okmh0uPg", [301, 244]
			],
			["mmv.ui.download.pane", "RHZliKYz", [224, 302]],
			["mmv.ui.reuse.shareembed", "p4zpl0hg", [302]],
			["mmv.ui.tipsyDialog", "pkCQ9m2S", [301]],
			["mmv.bootstrap", "EZ70tcSO", [135, 228, 230, 308, 243]],
			["mmv.bootstrap.autostart", "iiLif1D+", [306]],
			["mmv.head", "Dpc9+PD0", [145]],
			["ext.QuickInsert", "ZJJEihDy", [296]],
			["ext.QuickInsert.admin", "R+o2LYyF", [296]],
			["ext.semanticforms.main", "9/3y1n5L", [315, 313, 324, 60, 61, 73]],
			["ext.semanticforms.browser", "B/4Bibij"],
			["ext.semanticforms.fancybox", "X9rFIQRK", [312]],
			["ext.semanticforms.dynatree", "g+vL+9kJ", [77]],
			["ext.semanticforms.autogrow", "JbAOgYSq"],
			["ext.semanticforms.popupformedit", "cljr36nF", [312]],
			["ext.semanticforms.autoedit", "c5UDwKkP"],
			["ext.semanticforms.submit", "7XbKBohi"],
			["ext.semanticforms.collapsible", "KHSgKuVv"],
			["ext.semanticforms.imagepreview", "6vKI7fV/"],
			["ext.semanticforms.checkboxes", "THe1Ag4W"],
			["ext.semanticforms.datepicker", "kVJKsOPW", [311, 62]],
			["ext.semanticforms.regexp", "DYR1W+Zu", [311]],
			["ext.semanticforms.select2", "4Bh4VGAe", [326, 175]],
			["ext.semanticforms.jsgrid", "+LmAy7kB", [73]],
			["ext.semanticforms", "gA3S5Cji"],
			["ext.semanticforms.SF_CreateProperty", "5CFeDoyb"],
			["ext.semanticforms.SF_PageSchemas", "mmenftJS"],
			["ext.semanticforms.SF_CreateTemplate", "oyElW1ay"],
			["ext.semanticforms.SF_CreateClass", "uG10IHwW"],
			["ext.semanticforms.SF_CreateForm", "c/5zjk1s"],
			["Base64.js", "JUEKM6Re"],
			["easy-deflate.core", "MuEHKKbn", [332]],
			["easy-deflate.deflate", "i/1B5Eym", [333]],
			["unicodejs", "O6V2l55d"],
			["unicodejs.wordbreak", "ZNdFZL/o", [335]],
			["papaparse", "eyMDKtKM"],
			["dom-classlist-shim", "U9hRAGte", [], null, null, "return!!('classList'in document.createElement('_')\u0026\u0026!(document.createElementNS\u0026\u0026!('classList'in document.createElementNS('http://www.w3.org/2000/svg','g'))));"],
			["rangefix", "PrD27c4H"],
			["ext.visualEditor.supportCheck", "ICorHmSX"],
			["ext.visualEditor.desktopArticleTarget.init", "0GXKwKIQ", [340, 347, 135, 144, 165, 103, 183, 145]],
			[
				"ext.visualEditor.desktopArticleTarget.noscript", "v9bMuSzZ"
			],
			["ext.visualEditor.targetLoader", "27aVvaHK", [347, 99]],
			["ext.visualEditor.desktopTarget", "DwOrp+a7"],
			["ext.visualEditor.desktopArticleTarget", "m4+UvgfD", [353, 344, 349, 175]],
			["ext.visualEditor.ve", "ayAiY9Ob"],
			["ext.visualEditor.track", "7TyibCle", [346]],
			["ext.visualEditor.base", "H2Ga0BwR", [346, 244, 335]],
			["ext.visualEditor.mediawiki", "naXFS8UZ", [348, 343, 562, 135, 144, 103, 145]],
			["ext.visualEditor.standalone", "CXqkJFXZ", [348, 39, 562]],
			["ext.visualEditor.data", "K+ngSOeo", [349]],
			["ext.visualEditor.core", "qb+DpJhs", [338, 348, 340, 25, 337, 339]],
			["ext.visualEditor.core.desktop", "7flbVKA6", [352]],
			["ext.visualEditor.switching", "8fzkQoAL", [244, 258]],
			["ext.visualEditor.mwcore", "3Waze6kW", [352, 354, 161, 175, 13, 145, 232]],
			["ext.visualEditor.mwformatting", "LbPJ0XXx", [355]],
			["ext.visualEditor.mwimage.core", "4aNmro5S", [355]],
			["ext.visualEditor.mwimage", "cThzncFp", [357, 142, 261, 264, 268]],
			["ext.visualEditor.mwlink", "BJtaWHYJ", [355]],
			[
				"ext.visualEditor.mwmeta", "urvwSNpU", [359, 167]
			],
			["ext.visualEditor.mwtransclusion.core", "LSukrJNd", [355]],
			["ext.visualEditor.mwtransclusion", "lZL+Zhsq", [361, 237]],
			["ext.visualEditor.language", "DLZlee3Z", [352, 562, 177]],
			["ext.visualEditor.mwalienextension", "ruG8ZRPw", [355]],
			["ext.visualEditor.mwgallery", "MO3upaA+", [355, 181, 264]],
			["ext.visualEditor.mwsignature", "IKaK3+cx", [362, 255]],
			["ext.visualEditor.experimental", "ZNdFZL/o", [363]],
			["ext.visualEditor.icons", "h5+z9+/5", [257, 258, 259, 260, 252, 253]],
			["ext.visualEditor.mytool", "xHaHiKWN", [362]],
			["skins.mediawikibootstrap", "ETDT1xbJ"],
			["skins.mediawikibootstrap1", "Xv/W0WFo"],
			["skins.mediawikibootstrap2", "xak2tJI3"],
			["skins.jshare", "zqLvrKQy"],
			["ext.joymescript.LevelTools.js", "cuR0jPF9"],
			["ext.joymescript.year.js", "MeNukZXq"],
			["ext.joymescript.ShowMsg.js", "mowxLGrP"],
			["ext.joymescript.actor-tab.js", "wY6ZANwD"],
			["ext.joymescript.CardSelect.js", "YFebFq4S"],
			["ext.joymescript.CardSelectTr.js", "683aJjJ6"],
			["ext.joymescript.lableLib.js", "RoBoDKD2"],
			[
				"ext.joymescript.rool.js", "hpMKLuA0"
			],
			["ext.joymescript.TabTag.js", "FzMhg+D7"],
			["ext.joymescript.w-lunbo.js", "hx9GSU1M"],
			["ext.joymescript.JoymeMovie.js", "vE2GmKyJ"],
			["ext.joymescript.giffer.js", "yuIyHacn"],
			["ext.joymescript.lunbo.css", "ztDcayCd"],
			["ext.joymescript.lunbo.js", "xGuF8FLD"],
			["ext.joymescript.week.js", "4X+rp1GO"],
			["ext.joymescript.canvas.js", "aQ58N1aQ"],
			["ext.joymescript.zhenrong.js", "sNX5oUGU"],
			["ext.joymescript.timer.js", "cOdjYCKu"],
			["ext.joymescript.counter.js", "xMnQp40I"],
			["ext.joymescript.counter.css", "/mFj0yGf"],
			["ext.ajaxpoll", "8MvSDBxE", [], "ext.ajaxpoll"],
			["ext.Ajaxpoll.New.css", "g8jCByUV"],
			["ext.MsUpload", "gNNKOA/C", [69]],
			["ext.Tabber", "S27H0q6B"],
			["ext.newTabber", "gv9JGiRg"],
			["ext.jlike.js", "sdf68ylY"],
			["ext.jcontribution.css", "Jprhnj9y"],
			["ext.jcontribution.js", "Ss/YeZq2"],
			["ext.jcomments.css", "nmsHQPHh"],
			["ext.jcomments.js", "SMb5l0t7"],
			["ext.jcomments.hot.css", "Kh0C2mj0"],
			["ext.jcomments.hot.js", "dcZjic6e"],
			["ext.voteNY.styles", "vcVeLpEM"],
			["ext.voteNY.scripts",
				"+5KjHely"
			],
			["ext.jquery.easing", "MqhCLD1q"],
			["ext.jquery.fancybox", "hPziNgHv", [408, 415]],
			["ext.jquery.multiselect", "ZLnROMSw", [57, 77]],
			["ext.jquery.multiselect.filter", "Qp9zCpFL", [410]],
			["ext.jquery.blockUI", "n2sKiA7H"],
			["ext.jquery.jqgrid", "ckor/sZR", [415, 57]],
			["ext.jquery.flot", "R0TiW3aA"],
			["ext.jquery.migration.browser", "IzYBOwB5"],
			["ext.srf", "/5xYW4hn", [549], "ext.srf"],
			["ext.srf.api", "VA/sT3QS", [416], "ext.srf"],
			["ext.srf.util", "Ov5fCcjt", [412, 416], "ext.srf"],
			["ext.srf.widgets", "UPkrwgju", [410, 416, 61, 72], "ext.srf"],
			["ext.srf.util.grid", "xIM9Nx9t", [413, 418, 75], "ext.srf"],
			["ext.jquery.sparkline", "vwAFzNgK", [415]],
			["ext.srf.sparkline", "vysUQCOg", [421, 418], "ext.srf"],
			["ext.dygraphs.combined", "t/Jbr54B"],
			["ext.srf.dygraphs", "GsHHCaX/", [423, 553, 418, 18]],
			["ext.jquery.listnav", "epv5/f3N"],
			["ext.jquery.listmenu", "gkaZHLH4"],
			["ext.jquery.pajinate", "Lvg2qcl6"],
			["ext.srf.listwidget", "i5cN7s+j", [418]],
			["ext.srf.listwidget.alphabet", "ZNdFZL/o", [425, 428]],
			["ext.srf.listwidget.menu", "ZNdFZL/o", [
				426, 428
			]],
			["ext.srf.listwidget.pagination", "ZNdFZL/o", [427, 428]],
			["ext.jquery.dynamiccarousel", "2qMXkgWH", [415]],
			["ext.srf.pagewidget.carousel", "CBUnrYyC", [432, 418]],
			["ext.jquery.jqplot.core", "gcnlwGvS", [415]],
			["ext.jquery.jqplot.excanvas", "RirnflM0"],
			["ext.jquery.jqplot.json", "zNKr5a69"],
			["ext.jquery.jqplot.cursor", "MiwboCiI"],
			["ext.jquery.jqplot.logaxisrenderer", "QItrxsFE"],
			["ext.jquery.jqplot.mekko", "I53P6z1N"],
			["ext.jquery.jqplot.bar", "wlHShh28", [434]],
			["ext.jquery.jqplot.pie", "NG+5jKWg", [434]],
			["ext.jquery.jqplot.bubble", "inJ/3G7X", [434]],
			["ext.jquery.jqplot.donut", "JS6FjBra", [441]],
			["ext.jquery.jqplot.pointlabels", "Vb08jFyx", [434]],
			["ext.jquery.jqplot.highlighter", "u7GIFltI", [434]],
			["ext.jquery.jqplot.enhancedlegend", "BEbLGQUM", [434]],
			["ext.jquery.jqplot.trendline", "pb94KQqA"],
			["ext.srf.jqplot.themes", "DrivpGyX", [25]],
			["ext.srf.jqplot.cursor", "ZNdFZL/o", [437, 455]],
			["ext.srf.jqplot.enhancedlegend", "ZNdFZL/o", [446, 455]],
			["ext.srf.jqplot.pointlabels", "ZNdFZL/o", [444, 455]],
			[
				"ext.srf.jqplot.highlighter", "ZNdFZL/o", [445, 455]
			],
			["ext.srf.jqplot.trendline", "ZNdFZL/o", [447, 455]],
			["ext.srf.jqplot.chart", "z2k13P/f", [434, 448, 418, 18]],
			["ext.srf.jqplot.bar", "WaiovtY6", [440, 454]],
			["ext.srf.jqplot.pie", "QAbhHHHh", [441, 454]],
			["ext.srf.jqplot.bubble", "R0tOd1Xf", [442, 454]],
			["ext.srf.jqplot.donut", "QAbhHHHh", [443, 454]],
			["ext.smile.timeline", "o5+AG8ew"],
			["ext.srf.timeline", "NKzlP/1T", [459, 223]],
			["ext.d3.core", "7NPAFGS+"],
			["ext.srf.d3.common", "IdM98CeJ", [418]],
			["ext.d3.wordcloud", "hSHLTJwA", [461, 462]],
			["ext.srf.d3.chart.treemap", "mSJOvi/o", [461, 462]],
			["ext.srf.d3.chart.bubble", "ixyjK+Le", [461, 462]],
			["ext.srf.jquery.progressbar", "I7teYlYy"],
			["ext.srf.jit", "yZCSjp/y"],
			["ext.srf.jitgraph", "UEWB4Sef", [467, 466, 223]],
			["ext.jquery.jcarousel", "lEo4fF/6", [415]],
			["ext.jquery.responsiveslides", "6b3f+Ov8"],
			["ext.srf.formats.gallery", "RqPa8xrC", [418]],
			["ext.srf.gallery.carousel", "8DI0N8+G", [469, 471]],
			["ext.srf.gallery.slideshow", "2qVUPHnp", [470, 471]],
			["ext.srf.gallery.overlay",
				"pq3FXF02", [409, 471]
			],
			["ext.srf.gallery.redirect", "OPpm7L9P", [471]],
			["ext.jquery.fullcalendar", "QThj9uMa"],
			["ext.jquery.gcal", "smcB0hzJ"],
			["ext.srf.widgets.eventcalendar", "moD32UzF", [553, 417, 418, 62, 72]],
			["ext.srf.hooks.eventcalendar", "/f0a9tMw", [416]],
			["ext.srf.eventcalendar", "bSE1Bkk2", [476, 479, 478]],
			["ext.srf.filtered", "lvWwSnsF"],
			["ext.srf.filtered.list-view", "/prPK+Q+", [481]],
			["ext.srf.filtered.table-view", "5MnH67ut", [481]],
			["ext.srf.filtered.calendar-view", "Rw9DbG+P", [476, 481]],
			["ext.srf.filtered.value-filter", "uua8gAuQ", [481]],
			["ext.srf.filtered.distance-filter", "5m0glKKP", [481, 72]],
			["ext.srf.slideshow", "FmTA56NB", ["mediawiki.legacy.ajax"]],
			["ext.jquery.tagcanvas", "ND55TuW/"],
			["ext.srf.formats.tagcloud", "qxihsXhX", [418]],
			["ext.srf.flot.core", "FLGdXndz"],
			["ext.srf.timeseries.flot", "EiQKSkdT", [414, 490, 418, 18]],
			["ext.jquery.jplayer", "VhPYUqdf"],
			["ext.jquery.jplayer.skin.blue.monday", "VzJFHo1K"],
			["ext.jquery.jplayer.skin.morning.light", "9ccGeh5j"],
			["ext.jquery.jplayer.playlist",
				"4YXBwg0h", [492]
			],
			["ext.jquery.jplayer.inspector", "LVrrsFe0", [492]],
			["ext.srf.template.jplayer", "f9WFQKld", [416]],
			["ext.srf.formats.media", "XC9XKx/9", [495, 497], "ext.srf"],
			["jquery.dataTables", "O8PMnLy+"],
			["jquery.dataTables.extras", "roUo/+Bm"],
			["ext.srf.datatables", "7nXRSKGa", [417, 418, 419, 499, 500]],
			["ext.srf.datatables.bootstrap", "XojRdZxU", [501]],
			["ext.srf.datatables.basic", "FmriOpHd", [501]],
			["ext.scribunto.errors", "Snu4JOpB", [63]],
			["ext.scribunto.logs", "lWyd5uTv"],
			["ext.scribunto.edit", "g+hsxMgJ", [48, 99]],
			["ext.socialprofile.userinfo.css", "rYr/gsNL"],
			["ext.socialprofile.userinfo.js", "CJWy/lfX"],
			["ext.socialprofile.clearfix", "mzUSwISP"],
			["ext.socialprofile.responsive", "9+w8dXSr"],
			["ext.socialprofile.flash", "l+QDQHj5"],
			["ext.socialprofile.LightBox", "+mgzw8Zu"],
			["ext.socialprofile.userboard.js", "OIcO4fJf", [244]],
			["ext.socialprofile.userboard.css", "PRCue6y6"],
			["ext.socialprofile.userboard.headskin.css", "lRdEI50R"],
			["ext.socialprofile.userboard.boardlist.css", "cbNHSVm5"],
			[
				"ext.socialprofile.userboard.boardlist.js", "GnbnLi/s", [244]
			],
			["ext.socialprofile.userrelationship.css", "c6o6I5dF"],
			["ext.socialprofile.userrelationship.js", "dn1HhawG"],
			["ext.socialprofile.userstats.css", "sO//PcM2"],
			["ext.socialprofile.useruserfollows.js", "K9kCkekd", [244]],
			["ext.socialprofile.useruserfollows.css", "nxFuLmc7"],
			["ext.socialprofile.userprofile.usercenter.js", "req26jU8"],
			["ext.socialprofile.userprofile.usercenter.css", "exUVbbd6"],
			["ext.socialprofile.userprofile.usercentercommon.css", "6Qgzwm7g"],
			["ext.socialprofile.userprofile.useraccount.css", "y2JIIjFK"],
			["ext.socialprofile.userprofile.useraccount.js", "taRDzaK8", [244]],
			["ext.socialprofile.userprofile.useruploadimg.js", "ceHY9ymg", [244]],
			["ext.socialprofile.userprofile.binderror.js", "lkGQVRZq", [244]],
			["ext.socialprofile.userprofile.action.js", "WuhRYQEx"],
			["ext.socialprofile.userprofile.bootstrap-datetimepicker.css", "gED2JHjx"],
			["ext.socialprofile.userprofile.bootstrap-datetimepicker.js", "optVGleR"],
			[
				"ext.socialprofile.userprofile.edit-select.css", "lZwQpr5B"
			],
			["ext.socialprofile.userprofile.uploadPreview.js", "PTfPV3NZ"],
			["ext.socialprofile.userprofile.jQuery.fileupload.css", "NwBJQwDE"],
			["ext.socialprofile.userprofile.userprofilepage.js", "AdluCn4X"],
			["ext.QuickMessage.js", "cjPTitIz"],
			["ext.QuickMessage.css", "utX63Nvs"],
			["ext.joymerecentchanges", "w5YUVJm5"],
			["ext.smw", "8j7dgFcY", [542], "ext.smw"],
			["ext.smw.style", "2TASgm6A", [552], "ext.smw"],
			["ext.jquery.async", "/XrXZ/hg", [], "ext.smw"],
			["ext.jquery.jStorage", "frGOIC5n", [92], "ext.smw"],
			["ext.jquery.md5", "x9B5fH8i", [], "ext.smw"],
			["ext.smw.dataItem", "9eKqlGqm", [540, 135, 144], "ext.smw"],
			["ext.smw.dataValue", "7RLsdyRO", [545], "ext.smw"],
			["ext.smw.data", "y5thamt2", [546], "ext.smw"],
			["ext.smw.query", "535qB4q2", [540, 147], "ext.smw"],
			["ext.smw.api", "HtRi69jM", [543, 544, 547, 548], "ext.smw"],
			["ext.jquery.qtip.styles", "lGz0Ucax", [], "ext.smw"],
			["ext.jquery.qtip", "2h0bzMku", [550], "ext.smw"],
			["ext.smw.tooltip.styles", "HQWD6PyO", [550], "ext.smw"],
			[
				"ext.smw.tooltip", "0TfjTr2D", [551, 540, 552], "ext.smw"
			],
			["ext.smw.tooltips", "ZNdFZL/o", [541, 553], "ext.smw"],
			["ext.smw.autocomplete", "yPCbU258", [60], "ext.smw"],
			["ext.smw.ask", "gz4p81fF", [555, 541, 553], "ext.smw"],
			["ext.smw.browse", "J8z6rJ1s", [555, 541], "ext.smw"],
			["ext.smw.property", "dMZmB5l1", [555], "ext.smw"],
			["pdfhandler.messages", "oA8H6Hwk"],
			["ext.semanticforms.wikieditor", "NxkA2a9e", [311, 284]],
			["ext.semanticforms.maps", "S/gCwJ9y"],
			["jquery.uls.data", "D1qWlXDh"]
		]);;
		mw.config.set({
			"wgLoadScript": "//wikicdn.joyme.com/xysw/load.php",
			"debug": !1,
			"skin": "mediawikibootstrap1",
			"stylepath": "//wikicdn.joyme.com/skins",
			"wgUrlProtocols": "bitcoin\\:|ftp\\:\\/\\/|ftps\\:\\/\\/|geo\\:|git\\:\\/\\/|gopher\\:\\/\\/|http\\:\\/\\/|https\\:\\/\\/|irc\\:\\/\\/|ircs\\:\\/\\/|magnet\\:|mailto\\:|mms\\:\\/\\/|news\\:|nntp\\:\\/\\/|redis\\:\\/\\/|sftp\\:\\/\\/|sip\\:|sips\\:|sms\\:|ssh\\:\\/\\/|svn\\:\\/\\/|tel\\:|telnet\\:\\/\\/|urn\\:|worldwind\\:\\/\\/|xmpp\\:|\\/\\/",
			"wgArticlePath": "/xysw/$1",
			"wgScriptPath": "/xysw",
			"wgScriptExtension": ".php",
			"wgScript": "/xysw/index.php",
			"wgSearchType": null,
			"wgVariantArticlePath": !1,
			"wgActionPaths": {},
			"wgServer": "http://wikicdn.joyme.com",
			"wgServerName": "wikicdn.joyme.com",
			"wgUserLanguage": "zh-hans",
			"wgContentLanguage": "zh-hans",
			"wgTranslateNumerals": !0,
			"wgVersion": "1.27.1",
			"wgEnableAPI": !0,
			"wgEnableWriteAPI": !0,
			"wgMainPageTitle": "首页",
			"wgFormattedNamespaces": {
				"-2": "媒体文件",
				"-1": "特殊",
				"0": "",
				"1": "讨论",
				"2": "用户",
				"3": "用户讨论",
				"4": "新游试玩WIKI 新游评测 最新游戏排行榜 新游视频直播",
				"5": "新游试玩WIKI 新游评测 最新游戏排行榜 新游视频直播讨论",
				"6": "文件",
				"7": "文件讨论",
				"8": "MediaWiki",
				"9": "MediaWiki讨论",
				"10": "模板",
				"11": "模板讨论",
				"12": "帮助",
				"13": "帮助讨论",
				"14": "分类",
				"15": "分类讨论",
				"102": "属性",
				"103": "属性讨论",
				"104": "Type",
				"105": "Type talk",
				"106": "Form",
				"107": "Form talk",
				"108": "概念",
				"109": "概念讨论",
				"828": "模块",
				"829": "模块讨论",
				"2300": "Gadget",
				"2301": "Gadget talk",
				"2302": "Gadget definition",
				"2303": "Gadget definition talk",
				"3000": "推荐"
			},
			"wgNamespaceIds": {
				"媒体文件": -2,
				"特殊": -1,
				"": 0,
				"讨论": 1,
				"用户": 2,
				"用户讨论": 3,
				"新游试玩wiki_新游评测_最新游戏排行榜_新游视频直播": 4,
				"新游试玩wiki_新游评测_最新游戏排行榜_新游视频直播讨论": 5,
				"文件": 6,
				"文件讨论": 7,
				"mediawiki": 8,
				"mediawiki讨论": 9,
				"模板": 10,
				"模板讨论": 11,
				"帮助": 12,
				"帮助讨论": 13,
				"分类": 14,
				"分类讨论": 15,
				"属性": 102,
				"属性讨论": 103,
				"type": 104,
				"type_talk": 105,
				"form": 106,
				"form_talk": 107,
				"概念": 108,
				"概念讨论": 109,
				"模块": 828,
				"模块讨论": 829,
				"gadget": 2300,
				"gadget_talk": 2301,
				"gadget_definition": 2302,
				"gadget_definition_talk": 2303,
				"推荐": 3000,
				"媒体": -2,
				"对话": 1,
				"用户对话": 3,
				"图像": 6,
				"档案": 6,
				"image": 6,
				"image_talk": 7,
				"图像对话": 7,
				"图像讨论": 7,
				"档案对话": 7,
				"档案讨论": 7,
				"文件对话": 7,
				"模板对话": 11,
				"帮助对话": 13,
				"分类对话": 15,
				"property": 102,
				"property_talk": 103,
				"concept": 108,
				"concept_talk": 109,
				"media": -2,
				"special": -1,
				"talk": 1,
				"user": 2,
				"user_talk": 3,
				"project": 4,
				"project_talk": 5,
				"file": 6,
				"file_talk": 7,
				"mediawiki_talk": 9,
				"template": 10,
				"template_talk": 11,
				"help": 12,
				"help_talk": 13,
				"category": 14,
				"category_talk": 15,
				"module": 828,
				"module_talk": 829
			},
			"wgContentNamespaces": [0],
			"wgSiteName": "新游试玩WIKI_新游评测_最新游戏排行榜_新游视频直播",
			"wgSiteGameTitle": "",
			"wgDBname": "xyswwiki",
			"wgExtraSignatureNamespaces": [],
			"wgAvailableSkins": {
				"vector": "Vector",
				"mediawikibootstrap": "MediaWikiBootstrap",
				"mediawikibootstrap1": "MediaWikiBootstrap1",
				"mediawikibootstrap2": "MediaWikiBootstrap2",
				"jshare": "JShare",
				"fallback": "Fallback",
				"apioutput": "ApiOutput"
			},
			"wgExtensionAssetsPath": "//wikicdn.joyme.com/extensions",
			"wgCookiePrefix": "homewiki",
			"wgCookieDomain": "",
			"wgCookiePath": "/",
			"wgCookieExpiration": 15552000,
			"wgResourceLoaderMaxQueryLength": -1,
			"wgCaseSensitiveNamespaces": [2302, 2303],
			"wgLegalTitleChars": " %!\"$&'()*,\\-./0-9:;=?@A-Z\\\\\\^_`a-z~+\\u0080-\\uFFFF",
			"wgResourceLoaderStorageVersion": 1,
			"wgResourceLoaderStorageEnabled": !1,
			"wgResourceLoaderLegacyModules": [],
			"wgForeignUploadTargets": [],
			"wgEnableUploads": !0,
			"srf-config": {
				"version": "2.3",
				"settings": {
					"wgThumbLimits": [120, 150, 180, 200, 250, 300],
					"srfgScriptPath": "//wikicdn.joyme.com/extensions/SemanticResultFormats"
				}
			},
			"wgWikiEditorMagicWords": {
				"redirect": "#重定向",
				"img_right": "右",
				"img_left": "左",
				"img_none": "无",
				"img_center": "居中",
				"img_thumbnail": "缩略图",
				"img_framed": "有框",
				"img_frameless": "无框"
			},
			"wgMultimediaViewer": {
				"infoLink": "//mediawiki.org/wiki/Special:MyLanguage/Extension:Media_Viewer/About",
				"discussionLink": "//mediawiki.org/wiki/Special:MyLanguage/Extension_talk:Media_Viewer/About",
				"helpLink": "//mediawiki.org/wiki/Special:MyLanguage/Help:Extension:Media_Viewer",
				"useThumbnailGuessing": !1,
				"durationSamplingFactor": !1,
				"durationSamplingFactorLoggedin": !1,
				"networkPerformanceSamplingFactor": !1,
				"actionLoggingSamplingFactorMap": !1,
				"attributionSamplingFactor": !1,
				"dimensionSamplingFactor": !1,
				"imageQueryParameter": !1,
				"recordVirtualViewBeaconURI": !1,
				"tooltipDelay": 1000
			},
			"wgMediaViewer": !0,
			"wgMediaViewerIsInBeta": !1,
			"wgVisualEditorConfig": {
				"disableForAnons": !1,
				"preferenceModules": {
					"visualeditor-enable-experimental": "ext.visualEditor.experimental"
				},
				"namespaces": [2, 0],
				"signatureNamespaces": [],
				"pluginModules": ["ext.cite.visualEditor"],
				"defaultUserOptions": {
					"defaultthumbsize": 300
				},
				"blacklist": {
					"msie": [
						["<=", 8]
					],
					"android": [
						["<", 3]
					],
					"firefox": [
						["<=", 14]
					],
					"safari": [
						["<=", 6]
					],
					"opera": [
						["<", 12]
					],
					"blackberry": null,
					"silk": null
				},
				"skins": ["vector", "apex", "monobook", "minerva", "blueprint", "mediawikibootstrap", "mediawikibootstrap1", "vector", "joyme1"],
				"tabPosition": "before",
				"tabMessages": {
					"edit": null,
					"editsource": "visualeditor-ca-editsource",
					"create": null,
					"createsource": "visualeditor-ca-createsource",
					"editlocaldescriptionsource": "visualeditor-ca-editlocaldescriptionsource",
					"createlocaldescriptionsource": "visualeditor-ca-createlocaldescriptionsource",
					"editsection": null,
					"editsectionsource": "visualeditor-ca-editsource-section"
				},
				"singleEditTab": !1,
				"showBetaWelcome": !0,
				"enableTocWidget": !1,
				"svgMaxSize": 5120,
				"namespacesWithSubpages": [true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true,
					true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
				],
				"specialBooksources": "特殊:网络书源",
				"restbaseUrl": !1,
				"fullRestbaseUrl": !1,
				"feedbackApiUrl": !1,
				"feedbackTitle": !1
			},
			"smw-config": {
				"version": "2.3.1",
				"settings": {
					"smwgQMaxLimit": 10000,
					"smwgQMaxInlineLimit": 1000,
					"namespace": {
						"属性": 102,
						"属性讨论": 103,
						"Type": 104,
						"Type_talk": 105,
						"概念": 108,
						"概念讨论": 109,
						"": 0,
						"Talk": 1,
						"User": 2,
						"User_talk": 3,
						"Project": 4,
						"Project_talk": 5,
						"File": 6,
						"File_talk": 7,
						"MediaWiki": 8,
						"MediaWiki_talk": 9,
						"Template": 10,
						"Template_talk": 11,
						"Help": 12,
						"Help_talk": 13,
						"Category": 14,
						"Category_talk": 15,
						"推荐": 3000
					}
				},
				"formats": {
					"table": "表格",
					"list": "列表",
					"ol": "有序列表项目",
					"ul": "无序列表项目",
					"category": "类别",
					"embedded": "嵌入型页面内容",
					"template": "模板",
					"feed": "RSS和Atom订阅",
					"csv": "CSV导出",
					"dsv": "DSV导出",
					"json": "JSON导出",
					"rdf": "RDF导出",
					"icalendar": "iCalendar导出",
					"vcard": "vCard导出",
					"bibtex": "BibTeX导出",
					"calendar": "月历",
					"eventcalendar": "事件日历",
					"eventline": "事件轴",
					"timeline": "时间轴",
					"outline": "大纲",
					"gallery": "图库",
					"jqplotchart": "jqPlot图表",
					"jqplotseries": "jqPlot系列",
					"sum": "数值之和",
					"average": "数值的平均值",
					"min": "最小数目",
					"max": "最大数目",
					"median": "数值的中位数",
					"product": "数值的乘积",
					"tagcloud": "标签云",
					"valuerank": "取值排名",
					"array": "数组",
					"tree": "树",
					"ultree": "Ultree",
					"oltree": "Oltree",
					"d3chart": "D3图表",
					"latest": "最近时间",
					"earliest": "最早时间",
					"filtered": "已过滤",
					"slideshow": "幻灯片",
					"timeseries": "时间序列图表",
					"sparkline": "Sparkline图表",
					"listwidget": "列表小工具",
					"pagewidget": "页面小部件",
					"dygraphs": "Dygraphs图表",
					"media": "媒体播放器",
					"datatables": "数据表"
				}
			}
		});
		var RLQ = window.RLQ || [];
		while(RLQ.length) {
			RLQ.shift()();
		}
		window.RLQ = {
			push: function(fn) {
				fn();
			}
		};
		window.NORLQ = {
			push: function() {}
		};
	}
	script = document.createElement('script');
	script.src = "//wikicdn.joyme.com/xysw/load.php?debug=false&lang=zh-hans&modules=jquery%2Cmediawiki&only=scripts&skin=mediawikibootstrap1&version=P3r3aZ%2FE";
	script.onload = script.onreadystatechange = function() {
		if(!script.readyState || /loaded|complete/.test(script.readyState)) {
			script.onload = script.onreadystatechange = null;
			script = null;
			startUp();
		}
	};
	document.getElementsByTagName('head')[0].appendChild(script);
}());